### ISSUE TITLE
all times error Error

### ISSUE THREAD

**Issue by terrytornado** [neumino/rethinkdbdash#102]
Hi, i have reThinkDB running in a VMWare Player (Debian) on my windows machine.

Most times i run a query against the db server i can see in the node console the following error:

ReqlDriverError: Failed to connect to 192.168.100.19:28015
Full error:
{
  "code": "ETIMEDOUT",
  "errno": "ETIMEDOUT",
  "syscall": "connect"
}.
    at Socket.<anonymous> (d:\Entwicklung2\AngularJS\caatoo\server\node_modules\rethinkdbdash\lib\connection.js:89:12)
    at Socket.g (events.js:199:16)
    at Socket.emit (events.js:107:17)
    at net.js:459:14
    at process._tickCallback (node.js:355:11)
Exiting slow growth mode

AN idea what i do wrong?

thanks
Stephan

**Comment by neumino** [comment]
Your VM probably cannot handle all the connections (it seems to be able to handle some connection since it exits slow growth).

Try
```
var r = require('rethinkdbdash')({max: 100})
```
Maybe it will avoid opening too many connections to your VM.

Or you need to properly configure your firewall/ports for your VM.
