### ISSUE TITLE
MALFORMED PROTOBUF (missing field `type`)

### ISSUE THREAD

**Issue by OriginalEXE** [neumino/rethinkdbdash#104]
Hello,

I am using Thinky but I believe the issue is related to rethinkdbhash so I am posting the issue here.

I am getting the error above, full error here:

	server-0 (err): Possibly unhandled ReqlClientError: MALFORMED PROTOBUF (missing field `type`):
	server-0 (err):     at Connection._processResponse (/var/www/modding/node_modules/thinky/node_modules/rethinkdbdash/lib/connection.js:171:35)
	server-0 (err):     at Socket.<anonymous> (/var/www/modding/node_modules/thinky/node_modules/rethinkdbdash/lib/connection.js:129:14)
	server-0 (err):     at Socket.emit (events.js:95:17)
	server-0 (err):     at Socket.<anonymous> (_stream_readable.js:748:14)
	server-0 (err):     at Socket.emit (events.js:92:17)
	server-0 (err):     at emitReadable_ (_stream_readable.js:410:10)
	server-0 (err):     at emitReadable (_stream_readable.js:406:5)
	server-0 (err):     at readableAddChunk (_stream_readable.js:168:9)
	server-0 (err):     at Socket.Readable.push (_stream_readable.js:130:10)
	server-0 (err):     at TCP.onread (net.js:528:21)

The query that causes the error:
`User.getAll( r.args( [ '6564d830-6149-42db-953c-c63977228e39'	] ) )`
(User is a Thinky model)

I am using the latest version of rethinkdb (rethinkdb 2.0.3~0trusty (GCC 4.8.2))

I tried googling but all I can find mentions that issue above might happen in case driver and db version are not both updated to their latest versions, but I believe that's not the case.

Do you have any idea what might be causing this error?

Thanks

**Comment by neumino** [comment]
Hello @OriginalEXE 

This happens when the driver/server are out of sync. The driver x.y.<anything> will work with any version of rethinkdb that are x.y.<anything>.
Did you restart rethinkdb after updating it? Can you try to update thinky/rethinkdbdash?


This works fine for me:
```
var thinky = require('./lib/thinky.js')();
var type = thinky.type;
var r = thinky.r;

var Model = thinky.createModel('test', {
  id: String,
});

Model.getAll(r.args(['89e2af70-f308-4c9a-9f64-173044b557b2'])).run()
    .then(function(result) {
  console.log(result);
});
```

**Comment by OriginalEXE** [comment]
Hi, thanks for your quick answer.

You just helped me realize my problem, I nowhere defined the r, and it appears that's what caused the issue, once imported thinky to the same module and defined r as thinky.r, error no longer happens.

Thanks again, and thanks for your awesome libraries :)

**Comment by neumino** [comment]
`r.ags` should have thrown `cannot read property getAll from undefined`. How was `r` defined before?

**Comment by OriginalEXE** [comment]
Yes, that's what surprises me, it was not defined at all. I was testing the query directly in data explorer and then I copied it over to the script without thinking about defining the r.

I am not exactly sure why t did not notify me of the undefined variable r method.

**Comment by OriginalEXE** [comment]
Here is my whole file that caused this error:

	var User = require( '../models/user.server.model' )();

	var UserQueryFactory = module.exports = function UserQueryFactory( args ) {

		if ( ! args ) {

			return [];

		}

		var request = User;

		if ( args.id ) {

			if ( Array.isArray( args.id ) ) {

				request = request.getAll( r.args( args.id ) );

			} else {

				request = request.get( args.id );

			}

		} else if ( args.username ) {

			request = request.getAll( r.args( args.username ), { index: 'username' } );

		} else if ( args.email ) {

			request = request.getAll( r.args( args.email ), { index: 'email' } );

		}

		request.run().then( function( data ) {

			if ( ! data.length ) {

				return [];

			} else {

				return data;

			}

		});

	}

When ran, it does not notify me of r being undefined, I just get the error above. Once I imported thinky and defined r properly, the error is gone.
