### ISSUE TITLE
Can I stream a file in?

### ISSUE THREAD

**Issue by llambda** [neumino/rethinkdbdash#109]
Say I have a table 'files', and I want to upload a file via streams, say,
{ filename: 'file.jpg',
  data: binary data here
}

Is it possible to stream in the binary data portion? Or must it be a buffer in an object, e.g. how http://www.rethinkdb.com/docs/storing-binary/javascript/ says to do.

**Comment by llambda** [comment]
Never mind, I think that I just need to use .pluck, and didn't realize it was an object stream.

**Comment by llambda** [comment]
I think that I just need to use .pluck, and didn't realize at first that it was an object stream.

But no matter what I do in my writable/transform stream (just trying to console log the chunks), I get:

```
Unhandled rejection TypeError: Invalid non-string/buffer chunk
    at validChunk (_stream_writable.js:178:14)
    at StreamFile.Writable.write (_stream_writable.js:205:12)
    at ReadableStream.ondata (_stream_readable.js:521:20)
    at emitOne (events.js:77:13)
    at ReadableStream.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at ReadableStream.Readable.push (_stream_readable.js:110:10)
    at node_modules/rethinkdbdash/lib/stream.js:66:18
```

E.g.,

```
var fs = require('fs');
var stream = require('stream');
var util = require('util');
var Writable = stream.Writable;

function StreamFile(options) {
  if (!(this instanceof StreamFile)) {
    return new StreamFile(options);
  }
  Writable.call(this, options);
}
util.inherits(StreamFile, Writable);

StreamFile.prototype._write = function () {
	console.log(arguments)
}
r.table('test')
.toStream()
.pipe(new StreamFile())
```

This is on io.js v2.3.3.

**Comment by neumino** [comment]
Sorry I missed this question.

No you cannot stream a portion of the binary. RethinkDB protocol doesn't cover such cases.
