### ISSUE TITLE
Uncaught exception in net.connect

### ISSUE THREAD

**Issue by mbroadst** [neumino/rethinkdbdash#111]
We had a rest api where we defined a ```process.on('uncaughtException', ...);``` handler, and were unable to connect to a rethinkdb server leading the program to crash outright. It seems that the net.connect has error handlers attached to it, but just "once". As I explained on IRC it's somewhat difficult for me to reproduce this error, but when it happens it takes our entire system out.. please let me know if I can help further elucidate this issue.

**Comment by neumino** [comment]
Should be fixed in 2.0.17
