### ISSUE TITLE
Multiple Imports

### ISSUE THREAD

**Issue by chrismbeckett** [neumino/rethinkdbdash#112]
If I am importing rethinkdbdash across multple files, am I supposed to *execute* the module over and over again? Seems from the docs that you would only import and execute it once in my server.js script, and then create a singleton or pass it around? What is the suggested pattern for NodeJS?

**Comment by neumino** [comment]
You can create a file `rethinkdb.js` and have inside
```
module.exports = require('rethinkdbdash')();
```
Then import `rethinkdb.js` everywhere you need the driver.

**Comment by neumino** [comment]
(This basically create a singleton in `rethinkdb.js` and pass it to other files.
