### ISSUE TITLE
Unhandled rejection ReqlClientError: MALFORMED PROTOBUF (missing field `type`)

### ISSUE THREAD

**Issue by vioz** [neumino/rethinkdbdash#113]
@neumino #104 references this error. What was the decided upon solution? I tried upgrading to the latest version of rethinkdbdash, 2.0.17, and I am using `rethinkdb 2.0.4~0trusty (GCC 4.8.2)`.

**Comment by neumino** [comment]
What's the query?

**Comment by rasapetter** [comment]
@neumino I'm getting this as well, with rethinkdbdash v.2.0.18 and the same version of rethinkdb as @vioz. My query looks something like this:

```javascript
CollectionThing
.orderBy({index: 'createdAt'})
.filter(r.row('collectionId').eq('foobar'))
.then();
```

**Comment by neumino** [comment]
I can't reproduce that thinky 2.0.10, rethinkdbdash 2.0.18 and rethinkdb 2.0.4

Can you paste a full script that triggers this error?
