### ISSUE TITLE
Issue with Babel Async/Await

### ISSUE THREAD

**Issue by chrismbeckett** [neumino/rethinkdbdash#114]
FYI - I am trying to use this library with BabelJS in NodeJS. Below is a sample:

```js
class Blah {
  static async DoSomething() {
    let results = await r.table("someTable").run();
    console.log(JSON.stringify(results));
  }
}
```

When I try to run the program, an exception is throw:

"Annonymous function returned `undefined`. Did you forget a `return`?"

**Comment by chrismbeckett** [comment]
Hmmmm... more info. A prior call using async/await works, so there must be something in particular about this particular query. The real query is using a filter function, which is probably the culprit somehow?

```js
    let associations = await r.table(TABLE)
      .filter(function(association) {
        return
          association("profile")("name").match(nameMatch)
            .and(
            association("profile")("location").match(locationMatch)
          );
      })
      .pluck("id")
      .run();
```

??

**Comment by neumino** [comment]
Are you sure the function in the query using filter is the one in your code?

The filter function return undefined, which doesn't work.

**Comment by chrismbeckett** [comment]
Here is the query executing in the Data Explorer:

```js
r.db("hoamlife")
  .table("associations")
	.filter(function(association) {
    return
      association("profile")("name").match("^Becky's Corner$")
      .and(
        association("profile")("location").match("^Lynnwood, WA$")
      );
  })
```
The nameMatch and locationMatch variables are set in my code... in the sample here I have hard-coded them. The query works.

**Comment by neumino** [comment]
Are your variables set to be string or RegExp in your code? RegExp are not
supported.
Or are they functions instead of strings?

**Comment by neumino** [comment]
Can you provide a full script with await that throws the error?

**Comment by chrismbeckett** [comment]
Give me a couple of days and I will try to reproduce and share a gist with something from the test database.

**Comment by neumino** [comment]
Closing. Please provide as this is probably more an issue with babel than with the driver.

If you still have issues, please provide a babel script and I can try to take a look at it.
