### ISSUE TITLE
If you don't have to open connections, when are they closed?

### ISSUE THREAD

**Issue by andrerpena** [neumino/rethinkdbdash#117]
I just found out about this project... Good job.
I was wondering, when are the connections closed if you don't manually open them?
Thanks.

**Comment by neumino** [comment]
With basically the typo you fixed.

The pool will adds connection to keep `buffer` connections available if possible (as long as the total number of connections does not exceed `max`).
The pool behaves like a stack, so the connections at the bottom of the stack won't be used as long as you don't need them. In this case they will be removed after `timeoutGb` seconds.

Let me know if that didn't answer your question.

**Comment by andrerpena** [comment]
Haha... yes.. I went back to carefully read the docs, that's when I fixed the typo. I came here to answer my own question and close the issue.

It's worth mentioning that connections also are closed when you call `r.getPoolMaster().drain();`.

Thanks @neumino.

**Comment by neumino** [comment]
Yep :)
