### ISSUE TITLE
Better Errors for Change Feeds

### ISSUE THREAD

**Issue by weshoke** [neumino/rethinkdbdash#124]
For whatever reason, the errors passed through to change feeds differ from the errors reported by the rethink driver.

Rethink:
```
{
  "name": "RqlRuntimeError",
  "msg": "Connection is closed.",
  "frames": [],
  "message": "Connection is closed in:\nr.table(\"machines_92394023_23409902\").filter(function(var_0) { return var_0(\"source\").eq(\"packet\").and(r.branch(var_0.hasFields(\"layers\"), var_0(\"layers\").ne(0), true)); }).changes()(\"new_val\")\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^"
}
````

RethinkdbDash
```
{}
````

`err.toString()` gives a message, but the structure of a JS Error is non-existant
`[Error: The connection was closed before the query could be completed.]`

**Comment by neumino** [comment]
I'm not sure what you mean by the structure of a JS error is non-existant.
This prints a proper stacktrace if I kill my rethinkdb server.


```
var r = require('rethinkdbdash')({
  buffer: 1,
  max: 1
});
var assert = require('assert');

r.db('test').table('test').changes().run().then(function(feed) {
  feed.each(function(err, change) {
    if (err) {
      assert(err instanceof Error);
      console.log(err.toString());
      console.log(err.stack);
    }
    else {
      console.log(change);
    }
  });
}).error(function(err) {
  console.log(err);
});
```

**Comment by weshoke** [comment]
What I mean is the raw Rethink error has a lot more info than what comes out of Rethinkdbdash, which is a shame.

**Comment by neumino** [comment]
Oh, you mean the query that fails?

**Comment by neumino** [comment]
Ok besides the query that fails, I didn't see more information.
It's also now returning not a plain Error but a ReqlServerError.

Let me know if there was something else you had in mind @weshoke :)
