### ISSUE TITLE
Option for disabling "optional run()"

### ISSUE THREAD

**Issue by thelinuxlich** [neumino/rethinkdbdash#128]
Sometimes when I'm composing a dynamic query, I need to yield a function because inside I run some queries before returning the final result. With this "optional run()" feature when I yield it doesn't return the query for more composability, it already executes it.

**Comment by neumino** [comment]
Can you provide a script where the behavior is not the one you want?

**Comment by marshall007** [comment]
@neumino I've run into this before just using promises and agree it would be useful to make this behavior configurable:

```js
Promise.resolve()
.then(function () {
  return r.table('foo');
})
.then(function (query) {
  // kind of expect to still have a query expression here,
  // but currently you get back results
})
```

**Comment by thelinuxlich** [comment]
@marshall007 pretty much summed it up

**Comment by neumino** [comment]
There was an issue about disable the optional run but I somehow really cannot find it.

```
Promise.resolve()
.then(function () {
  return r.table('foo');
})
.then(function (query) {
})

// is equivalent to

Promise.resolve()
.then(function () {
  var query = r.table('foo');
})
```

In the case when the function is already defined
```
Promise.resolve()
.then(function () {
  return r.table('foo');
})
.then(cb)

// is equivalent to
Promise.resolve()
.then(function () {
  return cb(r.table('foo'));
})
```

You can't save the promise and expect it to return `r.table('foo')` again too. So am I missing something?

That being said, I'm not strongly opposed to adding an option to disable the optional `run`, it's not super-hard to do, but I have a  hard time figuring out a real use case.

**Comment by neumino** [comment]
By not super-hard, it's actually just adding this in `then`/`error`
```
if (option.disableOptionalRun) {
  return this;
}
```

**Comment by marshall007** [comment]
@neumino ok, here's a more real-worldish scenario where you might want to dynamically build some query based on other calls to the db.

```js
function build_query () {
  r.tableList().nth(0).run()
  .then(function (table_name) {
    return r.table(table_name);
  })
}

build_query().then(function (query) {
  // this will resolve with an array of results
  // rather than the expression so we can't
  // continue building a query
  return query.getAll(/* ... */).run();
})
```

Also in your example, `cb` will be called with an array of documents in the first case and a query expression in the second, so they would indeed differ.

**Comment by neumino** [comment]
Oh ok, that makes more sense now. Sounds something reasonable :+1:

**Comment by neumino** [comment]
Out in 2.1.2. Set `optionalRun: false` in the option to disable this feature.

Not that once disabled, it will also be disabled for other instances of `r` but that's probably not a common situation.
