### ISSUE TITLE
Only return generated ids from transform streams

### ISSUE THREAD

**Issue by Morgul** [neumino/rethinkdbdash#129]
I'm looking at inserting chunks of binary data into RethinkDB, meaning my documents will be ~25mb. Unfortunately the transform stream API either returns me the full documents, or nothing; there's no option for me to get back just the ids of the inserted documents. As these documents are large, I don't want to have to resend them over the wire just to get ids.

Additionally, it was very unclear from the documentation what the difference between the writable stream and transform stream was; it would be nice to clarify that the transform stream returns the objects. I'm still confused as to why transform streams even have the option not to return results? Wouldn't you just use a writable stream at that point?

**Comment by neumino** [comment]
Released in 2.1.3

You can do
```
var table = r.table('test').toStream({transform: true, format: 'primaryKey})
stream.pipe(table).pipre(...)
```

On a side note, I don't think storing 25mb binaries in RethinkDB is a good idea. It's probably better to save it on disk and save its path to the database.

**Comment by Morgul** [comment]
@neumino So, I just need to say that your turn around and responsiveness is impressive. Every time I end up running into an issue with one of your projects, you do an excellent job responding to the issue. Running a few open source projects myself, I know it's not always easy. So, seriously, thank you. :)

Now, about my insane idea. While you're most certainly right, the problem I've been tasked with solving is coming up with a good solution for storing generated PDFs. We currently have a SQL server / file system solution and it's terrible, brittle, and does not scale. We have more documents than size of any one physical disk, using a NAS causes all kinds of I/O issues, and we've even hit the limits of the NTFS file system a couple of times. In short, we need something that can scale better than a file system.

GridFS is the guy that everyone suggests, but it has some massive issues with concurrency. (Writing files isn't atomic, so requesting a currently writing file corrupts the file.) So, my current solution is to chunk files into manageable sizes, and hope RethinkDB fares better. (So far so good, but I'm still loading the test instance.) I could try cassandra, or hbase... but they need the files chunked manually as well, and if I'm going to do that, I'd rather use my personal favorite db, until I can prove it _can't_ handle it.

While this discussion probably should be taken up outside this issue, I figured I'd just explain my reasoning, and what I'm trying to do. :) (I'm on gitter in the rethinkdb channel, if you want to hit me up there.)

**Comment by neumino** [comment]
You can try https://github.com/ipfs/ipfs maybe?
Ipfs with rethinkdb -- not sure you can find a more bleeding edge stack than that :)
