### ISSUE TITLE
[2.1.x] missing ReQL updates

### ISSUE THREAD

**Issue by marshall007** [neumino/rethinkdbdash#132]
It looks like the following changes were missed from the 2.1 release:

- `r.union` is now a top-level term ([#4030](https://github.com/rethinkdb/rethinkdb/issues/4030))
- `condition.branch(...)` now works just like `r.branch(condition, ...)` ([#4438](https://github.com/rethinkdb/rethinkdb/issues/4438))

**Comment by neumino** [comment]
Thanks @marshall007 for tracking that. Push coming in a few minutes :)
