### ISSUE TITLE
Automatic Data Migration

### ISSUE THREAD

**Issue by zwhitchcox** [neumino/rethinkdbdash#139]
This is great! The only thing I don't like (and maybe you've already included this feature, idk), is that with Mongoose and MongoDb, there was automatic db migration. You just specify the model in the file, and it's automatically adjusted in the database. Is there any way you guys could do something like that?

Of course, there was also a downside to this, in that when you adjusted the model, you had to manually adjust the data. It would be *really* cool if you could find some way around that. Maybe just dropping the fields entirely.

Anyway, thanks for all your hard work!

**Comment by kulbirsaini** [comment]
@zwhitchcox check out [thinky](https://github.com/neumino/thinky) by @neumino.

**Comment by zwhitchcox** [comment]
Thanks, that's perfect! I wonder why people would choose this instead.

**Comment by kulbirsaini** [comment]
Sometimes your app may not demand well defined models.
