### ISSUE TITLE
RethinkDb file save option

### ISSUE THREAD

**Issue by zwhitchcox** [neumino/rethinkdbdash#140]
So this is kind of a shot in the dark, but would it be possible to specify the file-save location of the rethinkdb database file? For instance, if I had a git project, and I wanted the database file to be saved with the actual project, how would I do that? Kind of like Sqlite3. I have a feeling the response is going to be "use sqlite3", but hey, it's worth a shot!

**Comment by neumino** [comment]
Start rethinkdb with `-d <path>` and commit your path if you want to keep the data.

The alternative if reqlite but it currently doesn't sync to disk and it's not given that it will dump in JSON array the data.
