### ISSUE TITLE
Suggestion: automatically retry writes during failover

### ISSUE THREAD

**Issue by laggyluke** [neumino/rethinkdbdash#142]
I'm not sure if this is actually in the scope of rethinkdbdash, but it would be awesome to have this feature.

During a cluster reconfiguration (e.g. on automatic failover), there's always a brief window of write unavailability. Any attempt to insert/update a row during that period results in an error like this:

> ReqlOpFailedError: Cannot perform write: The primary replica is currently changing from one replica to another. The write was not performed. This error should go away in a couple of seconds

(there might be other similar errors, I haven't tested it thoroughly yet)

It would be great if rethinkdbdash was smart enough to automatically retry these queries, with randomized exponential backoff and some timeout.

**Comment by neumino** [comment]
This seems like a bad idea to me. You could have multiple writes in your query, and you probably don't want to retry all of them if only a few failed.

**Comment by laggyluke** [comment]
Yeah, I guess you're right and there's no way to implement this safely at the level of database driver.
I initially thought about a single document inserts/updates, but only adding autoretry to certain operations will only make matters more confusing.
