### ISSUE TITLE
Use of console.error() in pool_master

### ISSUE THREAD

**Issue by MarkHerhold** [neumino/rethinkdbdash#145]
It appears that if there is an issue draining connection pools, rethinkdbdash will [log the error using `console.error()`](https://github.com/neumino/rethinkdbdash/blob/722e8cc7759f89838bf28a89e46f67a6b84347e2/lib/pool_master.js#L510) instead of using the logger created from the helper.createLogger function [here](https://github.com/neumino/rethinkdbdash/blob/722e8cc7759f89838bf28a89e46f67a6b84347e2/lib/pool_master.js#L28).

Is there a reason for this or if it is just an oversight, could it be changed to use the helper?

**Comment by neumino** [comment]
Thanks

**Comment by MarkHerhold** [comment]
You rock @neumino!

**Comment by neumino** [comment]
Fixed in 2.1.7
