### ISSUE TITLE
Issues maintaining TLS conneciton

### ISSUE THREAD

**Issue by mwielbut** [neumino/rethinkdbdash#146]
Able to establish encrypted connection and execute queries but after the connection timeout (default 20 seconds) the driver throws up with a "write after end" exception. *Connecting to Compose.io DaaS*. 

Example:
``` javascript
var r = require('rethinkdbdash')(
{
      host: 'aws-us-east-1-portal.1.dblayer.com',
      port: 12345,
      authKey: '1234567890',
      ssl:
      {
            rejectUnauthorized: false
      }
});

r.table('tv_shows').run().then(function(result)
{
      console.log(result);
});
```

... wait 20 seconds...

``` bash
Creating a pool connected to aws-us-east-1-portal.1.dblayer.com:12345
Entering slow growth mode
Fail to create a new connection for the connection pool. Error:{"message":"Failed to connect to aws-us-east-1-portal.1.dblayer.com:12345 in less than 20s."}
Fail to create a new connection for the connection pool. Error:{"message":"Failed to connect to aws-us-east-1-portal.1.dblayer.com:12345 in less than 20s."}
Fail to create a new connection for the connection pool. Error:{"message":"Failed to connect to aws-us-east-1-portal.1.dblayer.com:12345 in less than 20s."}
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: write after end
    at writeAfterEnd (_stream_writable.js:167:12)
    at TLSSocket.Writable.write (_stream_writable.js:214:5)
    at TLSSocket.Socket.write (net.js:634:40)
    at /home/test/node_modules/rethinkdbdash/lib/connection.js:104:23
    at Object.tryCatch (/home/test/node_modules/rethinkdbdash/lib/helper.js:167:3)
    at TLSSocket.<anonymous> (/home/test/node_modules/rethinkdbdash/lib/connection.js:103:12)
    at TLSSocket.emit (events.js:129:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1001:10)

```

**Comment by neumino** [comment]
Can you run queries? If yes can you still run queries after 20 seconds? (normal queries, not changefeed).

**Comment by neumino** [comment]
The issue here is that the driver failed to open a connection (the handshake timed out - 20 secs)

**Comment by mwielbut** [comment]
Thanks for the quick response! Yup, able to run multiple queries. I even up'd the `timeout` value to 5 minutes and dropped our database - it stayed open for 5 min and created our database and tables on the server. I could then seed our data and run queries and updated from the app but once the 5 min ran out, it gave that error.

**Comment by mwielbut** [comment]
Either I was doing something wrong or something changed with the haproxy on Compose.io. Works this morning. Sorry for the trouble.

**Comment by neumino** [comment]
Glad it works now :)

**Comment by AdamBrodzinski** [comment]
@mwielbut how did you get this working on compose without the ssl key? Could you elaborate more on this? Issue #222 has the same problem and is a blocker for me.

Thanks!
Adam
