### ISSUE TITLE
change feed help

### ISSUE THREAD

**Issue by longraider007** [neumino/rethinkdbdash#148]
Hi,

I am new using the rethinkdbdash code, but I have a question regarding the change feed. 
How do I get the change feed to display in the console.log if I change one of the document in the table via rethinkdb data explorer?
I use the following code line, but it is not working.

r.db(db).table(table).changes().run().then(function(result){
	console.log(result);
});

_________________________________
my config.js 

module.exports = {
  rethinkdb: {
    host: '192.168.2.3',
    port: 28015,
    authKey: '',
    db: 'testing'
  },
  express: {
     port: 3000
  }
};
_____________________________________________________________
My app.js

var express = require('express'),
	app = express(),
	server = require('http').createServer(app),
	io = require('socket.io').listen(server),
	users = {},
	db='testing',
	table = 'todos';
var app = express();

//For serving the index.html and all the other front-end assets.
var config = require(__dirname + '/config.js');
var r = require('rethinkdbdash')(config.rethinkdb);
server.listen(80);

r.db(db).table(table).changes().run().then(function(result){
	console.log(result);
});

Thank you in advanced!!

**Comment by neumino** [comment]
Doc: http://rethinkdb.com/api/javascript/changes/

```
r.db(db).table(table).changes().run().then(function(feed){
  feed.each(console.log)
});
```
