### ISSUE TITLE
Easy way of handling disconnects

### ISSUE THREAD

**Issue by kaYcee** [neumino/rethinkdbdash#150]
In case of a single (predefined) connection I want to be able to handle connection state changes such as:
1. successfully established connection
2. cannot establish connection
3. connection established but dropped for some reason
4. re-established connection after disconnect

I figured cases 1 and 4 could be handled by listening to the <code>'created-connection'</code>-event of the first pool (<code>r.getPoolMaster().getPools()[0].on('created-connection', function(pool) {...});</code>

For cases 2 and 3 the following error is logged: <code>'Failed to create a new connection for the connection pool' </code>(pool.js:290). For the time being I added another event listener <code>self.emit('connection-error', self);</code> to pool.js right after the error msg to be able to handle both scenarios and inform the user accordingly.

Is there any better, recommended way to handle these four cases?

**Comment by neumino** [comment]
Hum, I'm not sure to understand what you are trying to do. You talk about a single predefined connection but mentions the pool. 

For a single connection
```
r.connect(...).then(function(conn) {
  // conn opened
  conn.on('error', function(err) {
    // conn dropped
  })
}).error(function(err) {
  // failed to open a new connection
})
```

**Comment by kaYcee** [comment]
I realize that my description might have been a little ambiguous....Basically I want to be able to tell if the status of a RethinkDB server is <b>'unreachable', 'just disconnected', 'just reconnected' or 'connected'</b> and want to inform the user accordingly. Now in case of a single server instance (ie. one host:port entry) a disconnect affects all pooled connections simultaneously, hence my simplification to 'single' connection.

My current solution picks the first connection and reacts on the emission of the <code>'connection-created'</code> event in case of  'connected' and 'reconnected' and on a customized <code>'connection-error'</code> event in case of 'disconnected' or 'unreachable' - which I then map to the info strings 'RethinkDB up/down'. But I am sure there must be a more elegant solution which I am hoping you can help me with.

In the end I would like to be able to handle multiple RethinkDB server instances and get real-time updates on their status changes. Thanks

**Comment by neumino** [comment]
Why do you want to access this information?
Why not just pull the data from server_status?

**Comment by neumino** [comment]
The reason why I'm asking is that things are actually a bit tricky.

Typically in discovery mode, if a pool doesn't have connections and cannot open a new one, it's just removed.
In non discovery mode, I believe the pool is just removed from the healthy pools.

But then a healthy pool may not have a connection (just after its creation)

**Comment by kaYcee** [comment]
I see. Well, thx for your replies - I'll just stick with my workaround for the time being and might in addition use the server_status table. Great tool!
