### ISSUE TITLE
Error goes to the result!

### ISSUE THREAD

**Issue by velocityzen** [neumino/rethinkdbdash#151]
Test:
```js
r.table('test')
  .insert({ id: 'test' })
  .run()
  .catch(function(err) {
     console.log('err', err);
   })
   .then(function(result) {
     console.log('result', result);
  });
```
First run gives us a normal insert result.
Second run gives us
```
result { deleted: 0,
  errors: 1,
  first_error: 'Duplicate primary key `id`:\n{\n\t"id":\t"test"\n}\n{\n\t"id":\t"test"\n}',
  inserted: 0,
  replaced: 0,
  skipped: 0,
  unchanged: 0 }
```
instead of an error!

**Comment by neumino** [comment]
This is expected. RethinkDB doesn't return an error in this case but a result with the error.
One of the reason is that you could have one write that fails while another one succeed.

**Comment by AdamBrodzinski** [comment]
I'm not sure I follow here....if you only call insert once and first_error is defined, does the driver re-try again? If not wouldn't it be best to throw and error and then let the user catch it if they want it to silently fail?

My use case is with GraphQL and i'm trying to figure out error flow here. If I don't throw it myself GraphQL thinks it's a success:

```javascript

     resolve(root, args) {
        return r.table('posts').insert(args, {returnChanges: true})
        .then((info) => {
          if (info.first_error) throw new Error(info.first_error)
          return info.changes[0].new_val;
        })
      }   
```

Unless i'm missing something it seems like a config to opt into this behavior  would be beneficial.

**Comment by neumino** [comment]
This is RetinkDB's behavior 
http://rethinkdb.com/api/javascript/insert/

To answer your question, the driver doesn't retry again after it gets an error.
If you want an error to be thrown if a write fail, you could write
```
r.table('test').insert({...}).do(function(result) {
  r.branch(
    result('errors').gt(0),
    r.error(result('first_error')),
    result
  )
})
```

**Comment by AdamBrodzinski** [comment]
Ok thanks!
