### ISSUE TITLE
pluck() not working with changes()

### ISSUE THREAD

**Issue by sstadelman** [neumino/rethinkdbdash#152]
I'm swapping in **rethinkdbdash** today, and I found that my query with changes() broke...  I use pluck() objects throughout my queries, and found that the query runs ok, if I remove the pluck() condition.

I initialized rethinkdbdash with `pool=true` and `cursor=true`. 

```javascript
r.table("users")
	.getAll(r.args(socket.user_profile.friends), {index: "email"})
	.pluck(pluck_fields)
	.changes()
	.run()
	.then(function(cursor) {
		cursor.each(function(err, row) {
			console.log('friend changed: ' + util.inspect(row.new_val));
			socket.emit("onFriendChanged", row.new_val);
		})
	})
	.error(function(err) { console.log("Failure:", err); })

var pluck_fields = {
        out_of_office: true,
        status: true,
        message: true,
        friends: true
    }
```
The printed query was:
```javascript
.table("users").getAll(r.args(["email1@test.com", "email2@test.com", "email3@test.com"]), {
    index: "email"
}).pluck({
        out_of_office: true,
        status: true,
        message: true,
        friends: true
}).changes()
```
Originally, my pluck object was a JSON object with `true` for each property name.  I tried trimming that down to just a single element `pluck('name')`, but still failed.

Then, I switched to the inverse:  `without('friends')`, and it works fine!

I don't know if the `pluck()` support is an issue, or if there is an inherent `hasFields()` being executed (not all documents have all fields...).

**Comment by neumino** [comment]
Hum, I just tried your script and things works fine for me.

Did you create your index `email`?
