### ISSUE TITLE
Notifications on connection open/close

### ISSUE THREAD

**Issue by weshoke** [neumino/rethinkdbdash#158]
Are there any analogous events emitted on the pool master to what's found in the Rethink API:
http://rethinkdb.com/api/javascript/event_emitter/

I'm trying to figure out the best way to know when all connections have failed and then have finally got started again.  I could use the rethink API directly, but that seems silly since there's already some nice wrappers here in rethinkdbdash.

The use case here is for changefeeds.  If the DB goes down, when it comes back up, I'd like to restart the changefeeds.  Without a notification that the connection is back, it's hard to see how to do this.

**Comment by neumino** [comment]
This is available in 2.1.9. The pool master emits a `healthy` event with `true` or `false` on whether the pool master is healthy or not.
