### ISSUE TITLE
Is there value in connecting rethinkdbdash pool exclusively to a local proxy node?

### ISSUE THREAD

**Issue by thelinuxlich** [neumino/rethinkdbdash#159]

**Comment by neumino** [comment]
I guess you are talking about RethinkDB's proxy.

I'm not sure, but I would say not really.
Basically when you connect rethinkdbdash to a RethinkDB server, this server acts like a proxy. If he doesn't host the data you need, your query will be rerouted.

Pinging @danielmewes -- Daniel may know more about the trade off, especially with raft. What is the cost of using a RethinkDB proxy? Does the proxy takes part in the raft protocol?

**Comment by danielmewes** [comment]
There are some queries where the CPU core handling a given connection can become the bottleneck. Spreading the load over multiple independent connections allows the RethinkDB proxy (or any RethinkDB server that you might connect to) to utilize multiple cores for those.
So there's still some value in using a connection pool, even when all connections go to the same proxy.
