### ISSUE TITLE
changes() is firing twice

### ISSUE THREAD

**Issue by mypark** [neumino/rethinkdbdash#161]
in this query, monitoring changes seems to be firing twice for each insert or delete
```
 r.table("users").getAll(r.args(favorites), {index: "name"}).changes().then(function(results) {
  //this fires twice for each change
}
```

**Comment by mypark** [comment]
nevermind - seems to be an issue with the socket.io wrapper around it I was using

**Comment by mypark** [comment]
When I'm using the rethinkdb node.js client with socket.io it seems to trigger double events when I'm monitoring changes.  It behaves correctly if I don't wrap it in a socket.io callback.  I set a debug on the code creating the connection,  it only goes through the connection code once so that doesn't seem to be the issue.

If I use the official js library and wait for the connection callback, I get the correct non-duplicated events.  However, if I use the node.js rethink driver with connection pooling, and wrapped in a socket io callback it seems to double up events, firing twice for each change.
```
    var r = require('rethinkdbdash')({db:'mydb'});
    // var r = require('rethinkdb');
    var app = require('express')();
    var http = require('http').Server(app);
    var io = require('socket.io')(http);
    var highlights = ["foo", "mike"];
    var connection = null;
    
    // this works correctly if I wait for the connection callback with the regular rethink js library, but doesn't work if I use the rethinkdbdash library
    // r.connect( {host: 'localhost', port: 28015, db:'mydb'}).then(function(conn) {
        
        // connection = conn;
        
        io.on('connection', function(socket){
          socket.on('chat message', function(msg){
            io.emit('chat message', msg);
          });
          
          console.log('connected');  //this connects only once as expected

          r.table("users").getAll(r.args(highlights), {index: "name"}).changes().then(function(results) {
        
            //this fires twice for some reason

            results.each(function(err,row) {
                  if (err) console.error(err);
                  
                  var prefix = row.new_val ? 'added' : 'deleted';
                  var msg =  row.new_val ?  row.new_val :  row.old_val;
                  console.log(prefix + ': ' +  msg.name);
                  io.emit('chat message', prefix + ': ' +  msg.name);
              });
           
          });
         });
      
      app.get('/', function(req, res){
        res.sendFile(__dirname + '/index.html');
      });
      http.listen(3000, function(){
        console.log('listening on *:3000');
      });
    // })
```

**Comment by neumino** [comment]
Aren't you just opening two socket io connections?
Can you provide a complete small test case (with the client side)?

**Comment by mypark** [comment]
I should be connecting only once - is there something in the code that I missed that means I'm connecting twice?  As for the client demo - I used this to connect:

https://github.com/rauchg/chat-example/blob/master/index.html

**Comment by neumino** [comment]
Works fine for me. The query is executed just once. You probably just connect twice to socket io...

**Comment by neumino** [comment]
If you still have an issue, please provide a full script including the front-end code.

**Comment by mypark** [comment]
did you try with the front end code included above?

**Comment by mypark** [comment]
Oh, nevermind - a piece of commented code wasn't actually commented out.  You are right - it's a non-issue.
