### ISSUE TITLE
support for `r.use`

### ISSUE THREAD

**Issue by mbroadst** [neumino/rethinkdbdash#162]
It seems rethinkdbdash differs from the official driver in that `r.use` is not supported. This is understandably difficult considering that there is a connection pool involved, but it would be incredibly helpful to find a way to include this functionality (especially for testing).

**Comment by neumino** [comment]
Hum, rethinkdbdash implements `use` as the official driver, via `connection.use`. `use` is not a top level term if I'm not mistaken.

Do you want `use` on a pool/all the pools?

**Comment by mbroadst** [comment]
oh you're totally right! hmm, I found myself in a situation where my business logic took a reference to `r` which when run in the context of the application is given a default database (e.g. `r = require('rethinkdbdash')({ db: 'something' })` ), but couldn't make that same expectation in my tests since I autogenerate the tables. My solution was to just fully recreate the rethinkdbdash for each test run that switches databases, which works fine, but it would be cool to just switch up the default db for all pools this way

**Comment by codydaig** [comment]
+1 I would love this to make testing easier!

**Comment by mbroadst** [comment]
@codydaig it turns out you can actually specify the db on 'run' to get the same effect

**Comment by codydaig** [comment]
@mbroadst Can you give me an example?

**Comment by neumino** [comment]
Something like
```
r.table('foo').run({db: 'bar'})
```
