### ISSUE TITLE
Building up query ASTs not possible?

### ISSUE THREAD

**Issue by jasonkuhrt** [neumino/rethinkdbdash#165]
One feature of I think all RethinkDB drivers is to enable a separation of concerns regarding query construction and query execution. It appears that `rethinkdbdash` has coupled them again if I am not mistaken. For example you used to be able to do:

```js
const fooTable = RQL.table('foo')
const mehFoo = fooTable.filter((doc) => doc('blah').eq('meh'))

/* ...later */

mehFoo.run(conn).then(...)
```

Am I missing something or is has `rethinkdbdash` taken a major departure away from this feature? Thanks! FYI I came to rethinkdbdash for the nice query queue feature and connection pooling.

**Comment by neumino** [comment]
Can you provide a full snippet of the issue?

**Comment by jasonkuhrt** [comment]
Example: I want to factor out `r.table('relations')` and `r.table('devices')` and `r.table('relations').getAll(id, { index: 'subject' })`. All are used extensively e.g.:

```js
device.delete = F.curry((r, id) => (
  Promise.all([
    r.table('devices').get(id).delete({ returnChanges: true }).then(getSingleDeletion),
    r.table('relations').getAll(id, { index: 'subject' }).delete({ returnChanges: true }).then(getMultiDeletion),
    r.table('relations').getAll(id, { index: 'observer' }).delete({ returnChanges: true }).then(getMultiDeletion),
  ])
  .then(F.apply(deviceModel))
))
```

**Comment by marshall007** [comment]
@jasonkuhrt neither of your examples illustrate this directly, but it sounds like you might be running into #128. You have to be careful when returning queries within promise chains for this reason.

**Comment by jasonkuhrt** [comment]
@marshall007 Yes partially but I think its more than just this. When I have time to rewrite some of my work with `rethinkdb` I'll paste more examples here. @neumino can you confirm that `rethinkdbdash` does not support building up AST snippets independent of a connection? I would deeply disagree with such an API if so. I think the ability to declaratively specify/compose queries apart from having the connection is a fantastic feature.

**Comment by neumino** [comment]
rethinkdbdash does support building partial queries/AST snippets.

**Comment by jasonkuhrt** [comment]
That's great to hear, can you show me an example of doing so independent of a connection?

**Comment by neumino** [comment]
Something like that?
```
var query1 = r.expr({foo: "bar"});
var query2 = query1.merge({hello: "world"});
query1.run().then(console.log);
query2.run().then(console.log);
```

**Comment by jasonkuhrt** [comment]
@neumino Yep. So:

```js
import RethinkDB from 'rethinkdbdash'
const r = RethinkDB() /* 1 */

const query1 = r.expr({foo: "bar"})
const query2 = query1.merge({hello: "world"})

query1.run().then(console.log)
query2.run().then(console.log)
```

But I thought `rethinkdbdash` automatically tries to connect at e.g. at `1` above?

**Comment by neumino** [comment]
I don't understand your question. What's the problem?

**Comment by neumino** [comment]
It does stat to create connection at `1` though.

**Comment by marshall007** [comment]
@jasonkuhrt oh, I think you're looking for `r = RethinkDB({ pool: false })`. If you specify that option, `rethinkdbdash` behaves like the official driver in that it won't spin up a connection pool and you'll be responsible for creating connections if/when you need to.

**Comment by jasonkuhrt** [comment]
@marshall007 Ah, yes, that might be exactly what I'm looking for. I'll report back this or next week. Thanks.

**Comment by neumino** [comment]
Closing since this is not an issue. Feel free to ask more question if needed.
