### ISSUE TITLE
includeInitial in .changes()

### ISSUE THREAD

**Issue by chocolat2000** [neumino/rethinkdbdash#176]
Hi,

Only 'squash' and 'includeStates' options seems available on the .change() command.
Adding 'includeInitial' would be interesting.

Ber.

**Comment by mbroadst** [comment]
@chocolat2000 should be a matter of adding it [here](https://github.com/neumino/rethinkdbdash/blob/master/lib/term.js#L520)

**Comment by neumino** [comment]
Closing as duplicate, let's track all the issue for 2.2 in one issue: #177
