### ISSUE TITLE
r.wait() doesn't accept any arguments

### ISSUE THREAD

**Issue by laggyluke** [neumino/rethinkdbdash#184]
This code:
```
r.wait({waitFor: 'ready_for_writes'}).run()
```
fails with the following error:
```
    ReqlDriverError: `r.wait` takes 0 argument, 1 provided.
      at Term._arity (/path/to/node_modules/rethinkdbdash/lib/term.js:2970:11)
      at r.wait (/path/to/node_modules/rethinkdbdash/lib/index.js:484:20)
      ...
```

I've actually discovered this when trying to work around another issue - `ready_for_writes` is not currently the default in rethinkdbdash, so `r.wait()` hangs indefinitely until absolutely all servers (and not just shards primaries) are online and up-to-date.

**Comment by neumino** [comment]
Thanks for the report, just pushed 2.2.1 with a fix.

**Comment by laggyluke** [comment]
Wow, that was quick! Thanks! :)
