### ISSUE TITLE
Working with identifying data types

### ISSUE THREAD

**Issue by AlaRuba** [neumino/rethinkdbdash#186]
I'm trying to use the data types with branching and updating. If the value is an array, I want to concatenate, and if the value is a string or number, I want to overwrite. For nested objects, I want the same behavior. Thus, I am using branching to differentiate types. However, it doesn't seem to be working properly.

Here is the branching logic, 

   r.branch(row(field).typeOf().eq('ARRAY'), row(field).add(data[field]),
                    r.branch(row(field).typeOf().eq('STRINGS') ,
                             data[field], deepcopy(data[field], row(field))));

Right now, deepcopy does nothing , but I see that arrays are getting passed to it. Is this logic wrong, or is this the wrong way to do branching?

**Comment by neumino** [comment]
`deepcopy` is a function in the driver, it doesn't get executed on the server.

i guess this is what you want:
```
r.branch(
  row(field).typeOf().eq('ARRAY'),
  row(field).add(data[field]),
  r.branch(
    row(field).typeOf().eq('STRINGS') ,
    data[field],
    r.expr(data).merge({field: row(field)})
  )
);
```

**Comment by neumino** [comment]
Closing the issue.
If you have more questions, feel free to ask here.

**Comment by AlaRuba** [comment]
I was unclear, but deepcopy is a function I wrote.

Your answer is close, but I don't think it can handle nested objects or objects nested in nested objects. I was wondering if you knew how to do this.

Thanks so much

**Comment by neumino** [comment]
What do you mean it doesn't handle nested objects? Can you provide an example of what the input/output is?
