### ISSUE TITLE
support eachAsync

### ISSUE THREAD

**Issue by xpepermint** [neumino/rethinkdbdash#188]
Please add [eachAsync](https://www.rethinkdb.com/api/javascript/each_async/) function - identical fashion to each, but returning a Promise.

**Comment by neumino** [comment]
In 2.2.2

**Comment by xpepermint** [comment]
Awesome!

**Comment by xpepermint** [comment]
@neumino there's an issue with the new method. The [callback](https://github.com/neumino/rethinkdbdash/blob/352f9684e0b725db643464414e2fb1040f228fcc/test/cursor.js#L111) should receive only one argument.

```js
cursor.eachAsync(function(row) {
// instead of 
cursor.eachAsync(function(err, row) {
```

Also the function does not return a promise. I get `[TypeError: Cannot read property 'then' of undefined]`.

```js
return cursor.eachAsync(function(row) {
   return Promise.resolve(1);
}).then(res => true);
```

**Comment by neumino** [comment]
My bad, I should have properly read the spec before implementing something.

**Comment by xpepermint** [comment]
Hehe, thx!

**Comment by xpepermint** [comment]
Perfect, works now ...
