### ISSUE TITLE
feed.close() stuck & error "currentResolve is not a function"

### ISSUE THREAD

**Issue by Bacto** [neumino/rethinkdbdash#190]
Hi,

First, I would like to thank you for this amazing driver :)

Unfortunately, I've encountered a bug :-/
Sometime when closing a feed, close is stuck and I get the error "currentResolve is not a function".

Example with a table with only 1 entry:
```
r.db('test').table('users')
	.insert({
		id: '0001d80b-eb4c-467a-ad1d-9f6bde59f814'
	})
	.run();
```

The above code will crash:
```
setInterval(function() {
	r.db('test').table('users')
		.get('0001d80b-eb4c-467a-ad1d-9f6bde59f814')
		.update({
			date: r.now()
		})
		.run();
}, 1000);


var cursorsOpened = 0;
setInterval(function() {
	if (cursorsOpened >= 5) {
		return;
	}

	r.db('test').table('users')
		.getAll('0001d80b-eb4c-467a-ad1d-9f6bde59f814')
		.changes({ includeInitial: true })
		.run(function(err, cursor) {
			cursorsOpened++;
			cursor.close(function() {
				cursorsOpened--;
			});
		});
}, 10);
```

The error:
```
TypeError: currentResolve is not a function
    at Connection._processResponse (node_modules/rethinkdbdash/lib/connection.js:393:7)
    at Socket.<anonymous> (node_modules/rethinkdbdash/lib/connection.js:149:14)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```

It happens when I update datas at the same time.
It doesn't happen if I replace `getAll` by `get` or if I set `includeInitial` to false.

I have no idea why.

**Comment by neumino** [comment]
I had a hard time to reproduce the bug, but if I have to set the first timer to 1ms it seems to always happen.
Thanks for the script!

**Comment by neumino** [comment]
If I log the token and response type, I get:

```
michel@xone:~/projects/rethinkdb-all/rethinkdbdash$ node test.js
Creating a pool connected to localhost:28015
1 1
2 3
2 2
2 2
4 3
3 1
4 2
4 2
5 1
6 1
7 1
9 3
8 1
9 3
9 2
10 1
11 1
12 1
13 1
14 1
15 1
16 1
17 3
17 3
17 2
18 1
19 1
20 1
21 1
22 1
23 1
24 1
25 1
28 3
28 2
28 2
26 1
27 1
29 1
30 1
31 1
32 1
33 1
37 3
34 1
35 1
36 1
37 2
37 2
38 1
39 1
40 1
41 1
42 1
43 1
44 1
47 3
47 2
45 1
46 1
48 1
49 1
50 1
55 3
51 1
52 1
55 2
55 2
53 1
54 1
56 1
57 1
58 1
59 1
60 1
61 1
62 1
63 1
64 1
65 1
66 1
67 1
68 1
69 1
70 1
71 1
72 1
73 1
74 1
75 1
76 1
77 1
78 1
79 1
80 1
81 1
82 1
83 1
84 1
85 1
86 1
87 1
88 1
89 1
90 1
47 3
```

For the token 47, I get a `SUCCESS_PARTIAL` after a `SUCESS_COMPLETE`.
@danielmewes -- is that working as intended? I thought that once a cursor/feed gets closed, and I have a pending `CONTINUE` query, two things can happen:
- I get pack `SUCCESS_PARTIAL` then `SUCCESS_SEQUENCE`
- Or I get two `SUCCESS_SEQUENCE`

@Bacto -- While we sort things out, I pushed 2.2.4 with a fix for now.

**Comment by Bacto** [comment]
Thank you very much @neumino!

I've made some tests today and it's much much better but I have sometimes again the error "currentResolve is not a function".

Unfortunately, I can't find a way to reproduce the bug :-/

**Comment by danielmewes** [comment]
> @danielmewes -- is that working as intended?

I'm not completely sure our of my head. Pinging @Tryneus and @mlucy.

**Comment by mlucy** [comment]
@danielmewes --

> For the token 47, I get a SUCCESS_PARTIAL after a SUCESS_COMPLETE.

I don't think that's intended behavior.
