### ISSUE TITLE
[Question] Multiple instances through 3th party libraries

### ISSUE THREAD

**Issue by Moeriki** [neumino/rethinkdbdash#195]
Dears,

This is a best practice and potential performance question.

rethinkdbdash is a dependency of two client libraries I might be using.
* [Thinky](https://thinky.io/) for ORM
* [session-rethinkdb](https://github.com/llambda/session-rethinkdb) for Express session storage

They both have an rethinkdbdash instance. Should I make them share this?

Thanks for your input.

**Comment by marshall007** [comment]
@Moeriki if you're using `npm@3.0`, dependencies are automatically flattened for you, so all instances of `rethinkdbdash` will be shared. If you're on an earlier version, you can use [`npm dedupe`](https://docs.npmjs.com/cli/dedupe).

**Comment by Moeriki** [comment]
You are right that the same module will be used. Two issues with that though.

1. NPM 3 will only flatten out where it can. If either project updates its dependency to a minor version different than the other this won't be shared any more. Can't base my logic on this.

2. rethinkdbdash will return [a new instance](https://github.com/neumino/rethinkdbdash/blob/master/lib/index.js#L525) of its internal `_r` whatsoever. So even when using the same module, there will still be two instances. Unless the pool is shared internally perhaps?

This aside I was rather wondering if I *should* invest in making them operate on the same instance. Regarding db efficiency, performance, etc.

It's certainly possible, and not that hard, as both expose their `r`. session-rethinkdb even allows you to pass an `r` instance when constructing.

**Comment by neumino** [comment]
You can have multiple instances (instantiation of `require('rethinkdbdash')`, it's fine but it's probably better to have one unique instance. It's easier to track errors and manage how many connection you want.

That being said, thinky doesn't let you provide an instance of `rethinkdbdash`, so I'll fix that :)

**Comment by neumino** [comment]
@Moeriki -- let me know if you have more questions

**Comment by Moeriki** [comment]
Thanks @neumino! [That was fast](https://github.com/neumino/thinky/commit/1fe1e86c0c8376479a14cd270864a80802b8883a) :smiley:
