### ISSUE TITLE
Question: Why is getLength() returning 1 if I have 3 replica instances running?

### ISSUE THREAD

**Issue by cggaurav** [neumino/rethinkdbdash#196]
```
r.getPoolMaster().getLength();
```

**Comment by neumino** [comment]
Because you are connecting to only one server. Did you pass `discovery: true` or multiple `servers` when creating the instances of rethinkdbdash?

**Comment by cggaurav** [comment]
Yes we do discovery:true  and I even see the servers in the dashboard.

**Comment by neumino** [comment]
What's the stdout output? And what version of RethinkDB are you running?

**Comment by neumino** [comment]
Also what does your cluster looks like?

**Comment by cggaurav** [comment]
This was because we hadn't configured discovery for rethinkdb-dash. Thanks @
neumino
