### ISSUE TITLE
 Warning: a promise was created in a  handler but was not returned from it

### ISSUE THREAD

**Issue by eportico** [neumino/rethinkdbdash#197]
'Warning: a promise was created in a  handler but was not returned from it'

This molest warning is frequenty in .then( use. Where are another use lib without Promise ?

**Comment by neumino** [comment]
Please provide a script that triggers this warning.

**Comment by eportico** [comment]
Estimations.table.group('_id2').run().then(function(results) {
      Pmvs.calculate( results, Estimations.estimationsPanel );
      return null;
    });

**Comment by roblav96** [comment]
try this:
```javascript
Estimations.table.group( '_id2' ).run().then( function ( results ) {
	return Pmvs.calculate( results, Estimations.estimationsPanel )
} )
```

**Comment by roblav96** [comment]
or maybe this
```javascript
return Estimations.table.group( '_id2' ).run().then( function ( results ) {
	return Pmvs.calculate( results, Estimations.estimationsPanel )
} )
```

**Comment by neumino** [comment]
This is working as intended and is an issue in your code, not in rethinkdbdash.

More information on bluebird's page.
http://bluebirdjs.com/docs/warning-explanations.html#warning-a-promise-was-created-in-a-handler-but-none-were-returned-from-it

**Comment by roblav96** [comment]
This plugin works flawless.

Take a look here to excel your promise skills:
http://pouchdb.com/2015/05/18/we-have-a-problem-with-promises.html

**Comment by eportico** [comment]
Thank to all. I review your comments

**Comment by eportico** [comment]
```  Pmvs.col.run().then(function(pmvs) {
      _.each(pmvs, function(p) {
        Pmvs.col.get(p._id).update({estimations: apply(grupos, p)},{durability: "soft"}).run();
      });
      console.log("end calculate estimations");
      return null;
    }).catch(function(err) {
      console.error(err);
    });
```

Generate many warnings of this type

**Comment by eportico** [comment]
```
  Pmvs.col.run().then(function(pmvs) {
      _.each(pmvs, function(p) {
        Pmvs.col.get(p._id).update({estimations: apply(grupos, p)},{durability: "soft"}).run();
      });
      console.log("end calculate estimations");
      return null;
    }).catch(function(err) {
      console.error(err);
    });
```

This code generate many Promise warnings

**Comment by neumino** [comment]
@eportico -- what version of rethinkdbdash are you using?
What's `Pmvs.col`? A table?

Can you provide a full script that I can run? If I use `loadash` and the last version of rethinkdbdash, I don't get any warnings.
