### ISSUE TITLE
code example for .changes()?

### ISSUE THREAD

**Issue by jamesjensen88** [neumino/rethinkdbdash#202]
When running this code:

```javascript
r.db('dbName')
.table('tableName')
.changes()
.run()
.then(function(res) {
    console.log(res)
})
```

'res' is a huge object with many keys, but I can't find the data from the db in it.

Could anyone provide a code example?

**Comment by neumino** [comment]
Rethinkdbdash provides the same API as the official driver except for a few things described in the README.
For changes, you get back a cursor:
http://rethinkdb.com/api/javascript/changes/
