### ISSUE TITLE
bad selector

### ISSUE THREAD

**Issue by eportico** [neumino/rethinkdbdash#203]
Field '_id' exist
Pmvs.col is a RethinkDB Table
```
Pmvs.col.forEach(function(p){
        return Pmvs.col.get(p("_id")).update({
          estimations: []
        }, {
          durability: "soft"
        }).run();
    }).run()
```
Unhandled rejection ReqlCompileError: Variable name not found in:
W20151211-09:44:54.969(1)? (STDERR) r.table("pmv_things").get(var_462("_id")).update({
W20151211-09:44:54.969(1)? (STDERR)                           ^^^^^^^
W20151211-09:44:54.969(1)? (STDERR)     estimations: []
W20151211-09:44:54.969(1)? (STDERR) }, {
W20151211-09:44:54.969(1)? (STDERR)    ^
W20151211-09:44:54.969(1)? (STDERR)     durability: "soft"
W20151211-09:44:54.969(1)? (STDERR)     ^^^^^^^^^^^^^^^^^^
W20151211-09:44:54.969(1)? (STDERR) })

**Comment by neumino** [comment]
The default primary key in rethinkdb in `id`, not `_id`.

**Comment by eportico** [comment]
In rehinkdb the default id is a optional name. In my tables is '_id'

**Comment by neumino** [comment]
Oh I see. Your query should be:
```
Pmvs.col.forEach(function(p){
        return Pmvs.col.get(p("_id")).update({
          estimations: []
        }, {
          durability: "soft"
        })
    }).run()
```
Note that there's only one call to `run`.

**Comment by eportico** [comment]
Eureka! Thank!
