### ISSUE TITLE
An option to wrap queries with r.wait()

### ISSUE THREAD

**Issue by thelinuxlich** [neumino/rethinkdbdash#205]
Because some use cases demand a incremental id which needs periodical rebalancing due to RethinkDB  only supporting range sharding

**Comment by neumino** [comment]
Let's track things on the rethinkdb tracker for this one.
https://github.com/rethinkdb/rethinkdb/issues/5208

I'm midly convince that this is a good idea. That means that in case you loose enough server, you will just wait forever.
