### ISSUE TITLE
No cursor recovery after a broken connection

### ISSUE THREAD

**Issue by niieani** [neumino/rethinkdbdash#207]
Hi @neumino.

I'm using changefeeds extensively in an environment where connectivity with the server on which rethinkdb server is running is very dodgy (often disconnects). The problem I'm having is that while the connection is reestablished, the cursors for the changefeeds are not recovered after such loss of connectivity. Do you have any ideas on how to mitigate this issue? Couldn't `rethinkdbdash` automatically "heal" the cursor with a new connection?

Thanks.

**Comment by neumino** [comment]
You can't heal a cursor at the moment, the main reason is because a cursor is bound to a connection (server side).

Cursor that automatically resume are on RethinkDB roadmap. I couldn't find the exact isssue but this is related:
https://github.com/rethinkdb/rethinkdb/issues/3471

**Comment by niieani** [comment]
I see. Well, I can reconnect and reestablish the cursor myself, but I need to have a way of telling that a cursor has died. Is there a way to do that? 
I've tried
```js
r.getPoolMaster().on('healthy', getNewCursor)
```
but that only works if all the connections die, not when the one cursor was using did.

**Comment by niieani** [comment]
I've also tried adding an event like this:
```js
cursor.once('error', waitForHealthyPoolAndGetNewCursor);
```
The problem is, the `error` event sometimes is not emitted when a connection dies. Not sure why. So far I just saw that when it's a cursor of a `.changes` subscription directly on a table (i.e. `r.table('abc').changes()`) the error event is usually emitted, but when the query is more complex, the `error` is not always emitted. That looks like a bug to me, unless I'm not understanding when the `error` event should be emitted by an open `cursor`?

**Comment by neumino** [comment]
When the connections dies*, the cursor also dies. Typically if you do
```
r.table('test').changes().run().then(function(feed) {
  feed.each(function(err, change) {
    // err will be an error if the connection dies.
  }
})
```

* The tricky part is if you don't see these errors, it's probably because the driver doesn't get any FIN packet from the connection. In which case detecting these disconnections depends on the configuration of your server. 
https://github.com/rethinkdb/rethinkdb/issues/4641 has a bit more information.

**Comment by niieani** [comment]
OK, thanks. So it's possible to catch errors when using `each`, but what if I'd like to use `eachAsync`? How in that case could I catch errors?

**Comment by neumino** [comment]
With 2.2.15:
```
cursor.eachAsync(...).error(function(error) {
  // handle operational error here.
})
```
