### ISSUE TITLE
Support arbitrary number of conditions for branch

### ISSUE THREAD

**Issue by mshi** [neumino/rethinkdbdash#208]
In 2.2.0, branch functionality has been extended to allow multiple conditions, but rethinkdbdash driver does not support this yet. Are there any plans for supporting this feature?

**Comment by neumino** [comment]
I didn't about this arity change. I'll update rethinkdbdash when I'll get
internet back (just moved to a new place)

**Comment by neumino** [comment]
Thanks for the report. Fixed in 2.2.14.
