### ISSUE TITLE
Drain on an unused pool blocks forever

### ISSUE THREAD

**Issue by bneijt** [neumino/rethinkdbdash#210]
The following code blocks forever:
```
var r = require('rethinkdbdash')();
r.getPoolMaster().drain();
```
iff there is no run() call inbetween.

node --version v5.1.0
rethinkdbdash@2.2.12 
bluebird@3.1.1 

The following program works:
```
var r = require('rethinkdbdash')();
r.dbList().run().then(console.log);
r.getPoolMaster().drain();
```

I would expect both programs to finish, but only the last will close.

**Comment by neumino** [comment]
Thanks for the report.
It's fixed in 2.2.13.
