### ISSUE TITLE
msg absent on error

### ISSUE THREAD

**Issue by NicolasParada** [neumino/rethinkdbdash#211]
With the rethinkdb driver I get an error object with `msg, message, frames, and name`, but with rethinkdbdash, `msg` is absent.
```javascript
function *() {
  try {
    yield r.error('My custom error.')
  } catch(ex) {
    this.type = 'json'
    this.body = { error: ex }
  }
}
```
I want to get the `msg` from `r.error`, but doen't exists in the catched `ex`.
I did a repo for reproduction here: [NicolasParada/rethinkdbdash-msg-absent](https://github.com/NicolasParada/rethinkdbdash-msg-absent)

**Comment by neumino** [comment]
`msg` is an internal-ish thing in the official driver. The error message is in `message`. If my memories serve me right, `message` is `msg` + the backtrace.

`rethinkdbdash` directly creates the `message` field (which is the standard field for the error message, not `msg`).

**Comment by NicolasParada** [comment]
Ok. I just was trying to do uniqueness like this:
```javascript
r.branch(
  r.db('base').table('users').getAll('JohnDoe', { index: 'username' }).count().gt(0),
  r.error('Username already exists.'),
  r.db('base').table('users').getAll('john.doe@demo.com', { index: 'email' }).count().gt(0),
  r.error('Email already exists.'),
  r.db('base').table('users').insert({ username: 'JohnDoe', email: 'john.doe@demo.com' })
)
```
And get the error message without all the query details...

**Comment by neumino** [comment]
You can still use a regex in this case.

**Comment by NicolasParada** [comment]
Ok.

**Comment by frankleng** [comment]
@neumino wondering if we can reopen this.
I'm using `r.branch(doc, doc, r.error(404))` to throw a 404 when doc is not found. so having access to `.msg` in this case helps the error handler deliver a proper 404 status code.
regexing seems a bit heavy.
thoughts?
