### ISSUE TITLE
ES6 Classes

### ISSUE THREAD

**Issue by niieani** [neumino/rethinkdbdash#213]
Hi Michel, 

Would you consider a pull request that converts rethinkdbdash to use classes and lambdas, according to the new EcmaScript 6 syntax? The main benefit is greater readability of the code (shorter and clearer) plus the semantic `this` (it would no longer be necessary to add `self` variables in most cases). Such code runs natively under `node` >=4. 
Those wanting to use rethinkdbdash with old node versions (versions 0.x), could simply use old versions of rethinkdbdash (I don't think anybody would want to start a new project using the old node 0.x), or use a transpiler like babel to get backwards-compatible code (also useful for usage in the browser).

**Comment by neumino** [comment]
Hum, not really, for two reasons:
- I don't know much about es6, but considering that node is built on v8, and that v8 is built for browsers, I would tend to think that they are not as optimized as the usual patterns.
- Ditching node 0.12.x seems a bit early to me.

**Comment by niieani** [comment]
There's very little new to learn about ES6, mostly it's syntactic sugar that makes the core more readable.

ES6 is now an official standard and the current version of JavaScript, so going forward the switch makes sense, if not today, then at least at some point.

If you're worried about ditching `node 0.x` or lack of optimizations (not sure if that one's entirely true, it looks like benchmarks show it [varies from feature to feature](https://kpdecker.github.io/six-speed/) - with some features getting speed benefits, some loosing out) we could have a pre-release `npm` script setup that generates an ES5 version by the means of transpilation (either via babel or typescript). In a couple of months the ES6 version should, in fact, be speedier when more optimizations get pulled by V8.
