### ISSUE TITLE
r.http "reattempts" param misspelt and incorrect

### ISSUE THREAD

**Issue by sagivf** [neumino/rethinkdbdash#215]
The correct param is `attempts`.
The confusion is probably due to a mistake in the docs:
https://github.com/rethinkdb/docs/issues/997

**Comment by sagivf** [comment]
Added pull request
https://github.com/neumino/rethinkdbdash/pull/216

**Comment by neumino** [comment]
Arg, thanks for catching that @sagivf!

**Comment by sagivf** [comment]
No prob :) thanks for the merge
