### ISSUE TITLE
error not catched by .error (or .catch)

### ISSUE THREAD

**Issue by jimoe** [neumino/rethinkdbdash#217]
In this code:
```
r
        .table(table)
        .get(id)
        .merge((pag) => {
          return {
            buckets: page('draft')('buckets')  
          }
        })
        .run()
        .then((result) => {...})
        .error((err) => {...})
```
I have a typo in the variable name.  It is declared as `pag`, and used as `page`.  

This error is not catch'ed by `.error` (or `.catch`).  I need to add `try{...} catch(e) {...}` around the query to catch the error.  I think that it should be catch'ed by `.error`

I am using version 2.2.17 of rethinkdbdash and node version 5.4.1

**Comment by neumino** [comment]
I think this is expected. We fail to build the query so we just throw. We will create and reject a promise only if the error is considered operational (like if you return an undefined value.
