### ISSUE TITLE
How do I connect to Compose.io?

### ISSUE THREAD

**Issue by nodesocket** [neumino/rethinkdbdash#222]
Compose.io shows a connection string of:

    rethinkdb://x:MY-TOKEN-HERE@aws-us-east-1-portal.4.dblayer.com:11078

I tried:

````
var r = require('rethinkdbdash')({
    database: 'my-db-here',
    discovery: true,
    timeout: 10,
    authKey: 'MY-TOKEN-HERE',
    servers: [
        {
            host: 'aws-us-east-1-portal.4.dblayer.com',
            port: 11078
        }
    ]
});
````

Getting:

````
Fail to create a new connection for the connection pool. Error:{"message":"Failed to connect to aws-us-east-1-portal.4.dblayer.com:11078 in less than 10s.","isOperational":true}
```

**Comment by neumino** [comment]
I don't have a compose account but don't they require SSL?

**Comment by nodesocket** [comment]
Got it working with:

```
var r = require('rethinkdbdash')({
    database: 'YOUR-DB-HERE',
    discovery: false,
    timeout: 10,
    authKey: 'COMPOSE-AUTH-KEY-HERE',
    servers: [
        {
            host: 'aws-us-east-1-portal.4.dblayer.com',
            port: 11078
        }
    ],
    ssl: {
        rejectUnauthorized: true
    }
});
```

**Comment by AdamBrodzinski** [comment]
@nodesocket How does that work without passing in the SSL cert from compose? (eg https://www.rethinkdb.com/api/javascript/connect/).  I'm out at the moment so I haven't tried to add `caCert` but I thought I would ask first.

Thanks!

**Comment by nodesocket** [comment]
So, I actually want to use SSL, since compose.io RethinkDB is in virginia and our node servers are in SF (AWS us-west-1).

Howerver, they only expose the SSL public key. Any idea how to get it working?

**Comment by nodesocket** [comment]
After further testing, I think I got closer.

```javascript
try {
    var publicKey = fs.readFileSync(__dirname + '/public-key.crt').toString().trim();
} catch(exception) {
    console.error('Failed to read file \'public-key.crt\'');
    process.exit(1);
}

var r = require('rethinkdbdash')({
    database: 'brandcast',
    discovery: false,
    timeout: 10,
    authKey: '',
    servers: [
        {
            host: 'aws-us-east-1-portal.4.dblayer.com',
            port: 11078
        }
    ],
    ssl: {
        ca: publicKey
    }
});
````

But now seeing an error:

```
    at Connection._processResponse (/home/node/tailr/node_modules/rethinkdbdash/lib/connection.js:235:19)
    at TLSSocket.<anonymous> (/home/node/tailr/node_modules/rethinkdbdash/lib/connection.js:156:14)
    at TLSSocket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at TLSSocket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
```

**Comment by AdamBrodzinski** [comment]
@neumino does this driver even support SSL? I wasn't sure if it was a superset of the original driver or a new re-write.

@nodesocket i've tried this as well and i'm just getting:

```javascript
var cert = fs.readFileSync(process.env.PWD + '/cert', 'utf8')


// Write your package code here!
rethinkdb = require('rethinkdbdash')({
  database: 'foo',
  discovery: false,
  timeout: 10,
  authKey: 'key1234',
  servers: [
    {
      host: 'aws-us-east-1-portal8.dblayer.com',
      port: 10024,
    }
  ],
  ssl: {
    ca: cert
  }
});
```

```
Creating a pool connected to aws-us-east-1-portal8.dblayer.com:10024
Entering slow growth mode
Fail to create a new connection for the connection pool. Error:{"message":"Failed to connect to aws-us-east-1-portal8.dblayer.com:10024\nFull error:\n{}.","isOperational":true}
Fail to create a new connection for the connection pool. Error:{"message":"Failed to connect to aws-us-east-1-portal8.dblayer.com:10024\nFull error:\n{}.","isOperational":true}
....
```

**Comment by nodesocket** [comment]
@AdamBrodzinski strange, I was able to get around that fail to create a new connection, by setting `discovery: false`, but now still have the issue:

```
    at Connection._processResponse (/home/node/tailr/node_modules/rethinkdbdash/lib/connection.js:235:19)
    at TLSSocket.<anonymous> (/home/node/tailr/node_modules/rethinkdbdash/lib/connection.js:156:14)
    at TLSSocket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at TLSSocket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
```

**Comment by AdamBrodzinski** [comment]
@nodesocket ah thanks... I get this:

```
telnet aws-us-east-1-portal8.dblayer.com 10024
Trying 54.x.x.xxx...
Connected to ec2-00-00-00-000.compute-1.amazonaws.com.
Escape character is '^]'.
```

The IP is whitelisted and I can also connect via the SSH tunnel but i'm having issues with the tunnel collapsing so i'd rather not use that if possible.

**Comment by neumino** [comment]
Sorry for the late answer, I was out of town.

As far as I know, connecting with ssl works. I'm not sure what @compose is giving you, but you should be able to pass a ssl field that is an object similar to what you pass to `tls.connect`
https://nodejs.org/api/tls.html#tls_tls_connect_options_callback

See the tests for examples (I just push an update for them to be easier to read):
https://github.com/neumino/rethinkdbdash/blob/master/test/tls.js

Can you actually connect with the official driver? The API for ssl is the same.

**Comment by alexeygolev** [comment]
This works for me with compose
``` javascript
const r = require('rethinkdbdash')({
  host: process.env.RDB_HOST,
  port: process.env.RDB_PORT,
  authKey: process.env.RDB_KEY,
  ssl: {
      ca: [fs.readFileSync(path.resolve(__dirname, '../cert'))]
    }
});

```
However I have to restart the app quite often because of the "Fail to create a new connection for the connection pool. Error:{"message":"Failed to connect to <dburl> in less than 20s.","isOperational":true}" error. Not sure if it's a compose.io specific issue.

**Comment by mwielbut** [comment]
Hi Adam,
Was able to get it working just fine the following settings:

```
            rethinkdb:
            {
                  host: 'xyz.dblayer.com',
                  port: 12345,
                  ssl:
                  {
                        ca: [ fs.readFileSync(__dirname+'/compose.pem') ]
                  },
                  authKey: "something secret",
                  db: "dbname",
                  timeoutError: 5000,
                  buffer: 5, 
                  max: 1000,
                  timeoutGb: 60 * 60 * 1000
            },
```

When I upgraded to use SSL with Compose I had to reach out to them to request they add the HAPROXY node and the 3rd failover. Not sure if that's the default setup for new RethinkDB deployments or if you still need them to manually request a change.
Then you should see a button in your deployment console to display the SSL key.

**Comment by AdamBrodzinski** [comment]
@mwielbut  I tried your config too but no go. @neumino I tried copy/pasting the config to official driver and it works (same cert too). I'll give this a few days and then I guess i'll have to switch.

**Comment by AdamBrodzinski** [comment]
@neumino Just tried rethinkdbdash in a new project and it works fine.. must be something with the Meteor app i'm running it in. Really weird. Thanks for all your time!

**Comment by nodesocket** [comment]
@mwielbut, thanks for sharing. I am also able to confirm the following setup works with Compose.io:

```
var r = require('rethinkdbdash')({
    host: 'aws-us-east-1-portal.4.dblayer.com',
    port: 11078,
    ssl: {
        ca: publicKey
    },
    authKey: 'AUTH-KEY-HERE',
    db: 'DB-HERE',
    timeoutError: 3000,
    buffer: 10,
    max: 100
});
```

This is strange though, because the official doc says the format is:

```
servers: [{
    host: '192.168.0.100',
    port: 28015
}]
```

**Comment by neumino** [comment]
This I believe should work too:
```
var r = require('rethinkdbdash')({
    servers: [{
        host: 'aws-us-east-1-portal.4.dblayer.com',
        port: 11078,
        ssl: {
             ca: publicKey
        }
    }]
    authKey: 'AUTH-KEY-HERE',
    db: 'DB-HERE',
    timeoutError: 3000,
    buffer: 10,
    max: 100
});
```

**Comment by mwielbut** [comment]
Update for anyone living in a post-v2.3 world with username and passwords now supported for authentication:

```
{
host: 'compose.io HOST (this is the proxy host)',
port: 12345, // compose.io PORT (this is the proxy port)
ssl:
{
    ca: [fs.readFileSync(__dirname + '/compose.io.pem').toString().trim()]
},
user: 'admin', 
password: "AUTH KEY", 
db: "DB NAME",
timeoutError: 5000,
buffer: 5, 
max: 1000,
timeoutGb: 60 * 60 * 1000
}
```

**Comment by devnetics** [comment]
@mwielbut This no longer seems to work. After a successful connection, on running a query nothing happens for me (using the Admin login that Compose first sets up). And yes, I have `.run()` at the end of my query, I double checked.
