### ISSUE TITLE
always trying connect to localhost

### ISSUE THREAD

**Issue by NPCRUS** [neumino/rethinkdbdash#223]
i'm trying to different options to connect to remote host :
1)
```
{
            servers :[
                {
                    host : '188.166.45.125',
                    port : 28015
                }],
            db : 'test',
        }
```
2) 
`{
            host : '188.166.45.125',
            port : 28015,
            db : 'test',
        }`

Bit in every situation it's trying to creating poll connection to localhost, what's wrong with my options?

**Comment by neumino** [comment]
What are the logs? Are you sure you are trying to connect to localhost?

**Comment by NPCRUS** [comment]
Creating a pool connected to 188.166.45.125:28015
Creating a pool connected to localhost:28015
Creating a pool connected to 188.166.45.125:28015
Creating a pool connected to localhost:28015
Creating a pool connected to 188.166.45.125:28015
Creating a pool connected to 188.166.45.125:28015
Creating a pool connected to 188.166.45.125:28015
Creating a pool connected to 188.166.45.125:28015
Creating a pool connected to 188.166.45.125:28015
Creating a pool connected to localhost:28015
Creating a pool connected to 188.166.45.125:28015
Creating a pool connected to 188.166.45.125:28015
Creating a pool connected to 188.166.45.125:28015
Creating a pool connected to 188.166.45.125:28015


After that, when he got a connection from remote url, instance trying to connect to localhost again and again. And complete all pool with refused localhost connections.

**Comment by neumino** [comment]
Are you creating multiple instances of `rethinkdbdash`?
Are you using `discovery; true`?
What does your cluster look like? One server only?
