### ISSUE TITLE
`eachAsync` throws if a promise is not returned

### ISSUE THREAD

**Issue by marshall007** [neumino/rethinkdbdash#225]
I think this is the line responsible: [`/lib/cursor.js#L278`](https://github.com/neumino/rethinkdbdash/blob/62084267e84c90adda77678ca8194e8305b09a49/lib/cursor.js#L278). It should probably be changed to something like `Promise.resolve(callback(data))`.

Here's an example to reproduce:

```js
cursor.eachAsync(function (row) {
  return;
})
// TypeError: Cannot read property 'then' of undefined
```

**Comment by neumino** [comment]
The problem with wrapping the return value with `Promise.resolve` is that if you write
```
cursor.eachAsync(function(row) {
  processRow(row) // forgot a return here
})
```

You end up with a tricky bug where you call processRow in parallel. That being said, I don't really have a strong opinion on that, and it's easy to do.

**Comment by marshall007** [comment]
@neumino good point. The use-case I encountered required conditionally processing some rows and returning otherwise. Currently you have to return an empty `Promise.resolve()` as a workaround, which is slightly annoying. It's also inconsistent with the behavior of the official driver. I'll submit a PR if you're ok with the proposed change.
