### ISSUE TITLE
filter returns all records if value is undefined

### ISSUE THREAD

**Issue by DiegoRBaquero** [neumino/rethinkdbdash#227]
The following code returns all admins

`````
r.table('admins').filter({field: undefined}).run().then((users) ->

).error (error) ->
    lg error
    res.status(400).send {error: error}
`````

This is a serious security bug. Using thinky 2.2.4.

**Comment by marshall007** [comment]
Hmm, so this behavior is intentional since `rethinkdbdash` strips out `undefined` values instead of throwing an error like the official driver, which is useful in the context of most operations.

@DiegoRBaquero what would you expect this to do? Convert the `undefined` value to `null`?

**Comment by DiegoRBaquero** [comment]
I'd expect it to throw an error or return empty as I do want to search by the field but the sent value was undefined so the filter should return empty.

**Comment by marshall007** [comment]
@DiegoRBaquero since `undefined` cannot be serialized to JSON, what you're doing is equivalent to `r.table('admins').filter({})`, which returns all rows in the official driver too.

**Comment by DiegoRBaquero** [comment]
But when you load a value from a JSON body and the value is not there -> undefined.

undefined values should be converted to null.

**Comment by neumino** [comment]
Like @marshall007 said, this is working as intended. 

`undefined` and `null` are two different things in JavaScript, and it's not the driver's responsability to guess what the desired value is. What you should do is check if the field is undefined first before sending the query.

Also you probably want to use an index, in which case calling `getAll(undefined, {index: "name"})` would throw an error as we can't serialize `undefined`.

**Comment by nardeas** [comment]
We recently ran into this issue as well. I think it's worth reconsidering this behavior. Similar issue was referenced here: https://github.com/rethinkdb/rethinkdb/issues/6338

with the conclusion that the official driver will fail. It's very easy to unintentionally pass an undefined value to a filter. If you're doing an update this might result in the update of all the records in the database. Example:

```javascript
r.db('prod').table('users').filter({ email: someObject.someTypoProperty }).update({ ... });
```

suppose `someObject.someTypoProperty === undefined` it's easy to see why it's a good idea to throw an error in this case.

I do understand the argument @neumino is making that you should always check for `undefined` before sending the query. But I think this is more of a question about disparity between the official driver and rethinkdbdash and also a little bit about developer friendliness.
