### ISSUE TITLE
orderBy bug

### ISSUE THREAD

**Issue by matjazgros** [neumino/rethinkdbdash#230]
When I use orderBy I get less records then expected. In table there is 5k+ records.

`r.table('metrics').orderBy({index: r.desc('updatedAt')}).slice(0,50)` returns around 20 records

`r.table('metrics').slice(0,50)` returns all 50 records

**Comment by neumino** [comment]
OrderBy with an index drops undefined and null values. Is that why?

**Comment by matjazgros** [comment]
I don't think so. All records have value (unix timestamp) in `updatedAt` field.

**Comment by neumino** [comment]
What does orderBy.count returns?

**Comment by matjazgros** [comment]
```
r.table('metrics')
    .orderBy({ index: r.desc('updatedAt') })
    .count()
```
returned `9670`

**Comment by neumino** [comment]
I can't reproduce this issue. Can you provide a script and a dataset where this happen?
