### ISSUE TITLE
Increase Verbosity/Debug Mode

### ISSUE THREAD

**Issue by 360disrupt** [neumino/rethinkdbdash#233]
I'm rewriting my code from mongodb to rethinkdb. So there are a lot of db operations and it is hard to tell for me what causes the error, if one occurs.

Is there a way to increase verbosity/to debug the app? I get errors like
 `Warning: a promise was created in a handler but was not returned from it`
or
`Unhandled rejection TypeError: Cannot read property 'new_val' of undefined``

they don't specifiy, which db operation, file, line number caused this error.

**Comment by neumino** [comment]
These are your errors propageted by bluebird, so there isn't much to do in rethinkdbdash

**Comment by 360disrupt** [comment]
Ok I will check there. I'm not using bluebird particulary but I guess `async` does. The problem seems to occur when using async & rethinkdb:
https://github.com/caolan/async/issues/974
