### ISSUE TITLE
Consider creating a CHANGELOG.md

### ISSUE THREAD

**Issue by chrisfosterelli** [neumino/rethinkdbdash#235]
It's a little more work to maintain a CHANGELOG, but from the perspective of a rethinkdbdash user it's a great help:

* I can easily pick out breaking changes when upgrading
* I can tell when a feature I'm looking for is supported
* I can see bug fixes / updates / etc at a glance

Whenever I'm updating a dependency the first thing I look for is a CHANGELOG, or else I mostly just "upgrade and pray". Of course it wouldn't be realistic to go back and populate all the previous versions, but a CHANGELOG.md with version 2.2.18 could be updated into the future as new releases come out.

If you're interested, I'm happy to create a PR with a simple CHANGELOG starter!

**Comment by neumino** [comment]
The changelog is in releases notes -- https://github.com/neumino/rethinkdbdash/releases
