### ISSUE TITLE
eachAsync.then() is never called

### ISSUE THREAD

**Issue by frankleng** [neumino/rethinkdbdash#241]
```
r.table('test').getAll([2,3], {index: 'test'}).changes({includeInitial: true})
.run()
.then(
  cursor => {
    cursor.eachAsync(row => {
        processRow(row);
      }
    ).then(() => {
      console.log('Done');
    })
  }
);
```

Can't seem to the reach the```eachAsync.then()``` block. @neumino please advise.

**Comment by neumino** [comment]
Hum, this is working as expected.

The changefeed never ends. so does the cursor, so your then handler is never called.

**Comment by frankleng** [comment]
@neumino what about when ``` { includeInitial: true } ```?
is there a way to capture the initial results at once? hacky way I found was just returning ```cursor._data```

**Comment by neumino** [comment]
You can use `includeStates` -- See:
http://rethinkdb.com/api/javascript/changes/

**Comment by frankleng** [comment]
Cool. Already using it.
Thought of it as a workaround but good to know this is the correct implementation.
