### ISSUE TITLE
thinky < 2.3.x depends on rethinkdbdash >= 2.3.0, making it useless with rethink < 2.3.x

### ISSUE THREAD

**Issue by mbroadst** [neumino/rethinkdbdash#243]
```
TypeError: Cannot read property 'success' of undefined
    at Socket.<anonymous> (<snip>/node_modules/rethinkdbdash/lib/connection.js:166:28)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:529:20)
```

This message is a bug on its own in rethinkdbdash itself, it should display the actual error returned from RethinkDB when its < 2.3.x (which is: "ERROR: Received an unsupported protocol version. This port is for RethinkDB queries. Does your client driver version not match the server?"). 

What is more of a concern is that my project was pegged at thinky `^2.2.4` which should have meant that  I was safe from the breaking protocol change in `2.3.x`, but apparently that wasn't followed.

**Comment by rsantosdev** [comment]
Same for me, I cant deploy anymore with this issue. package 2.2.7 should rely on rethinkdb 2.2.1

**Comment by mwielbut** [comment]
+1 - this issue is pretty serious. Can't do a deployment without upgrading DB.

**Comment by mbroadst** [comment]
I don't think there's a way around it at this point, you need to lock the version or do something like ~2.2.4 to keep it within the 2.2 versions.

**Comment by rsantosdev** [comment]
I will wait until @neumino fixes it. If not we will need to deploy a version with it. I will hold deploys until then

**Comment by mwielbut** [comment]
I was able to work around this by adding a rethinkdbdash dependency at the top level. Satisfies the dependency requirement in Thinky.
`"rethinkdbdash": "2.2.17",`

**Comment by rsantosdev** [comment]
As an workaround you can force `rethinkdbdash` on your `package.json` and run `npm dedupe` to avoid the issue

**Comment by rsantosdev** [comment]
I am forcing mine to be `"rethinkdbdash": "2.2.20"` and then `npm dedupe rethinkdbdash`

**Comment by neumino** [comment]
This is a thinky issue. But I just pushed 2.2.8 for that. I didn't pay attention to the package.json file when merging https://github.com/neumino/thinky/pull/420

Also thinky x.y.z is compatible with RethinkDB x.y only. RethinkDB doesn't follow the usual convention and thinky/rethinkdbdash are using their convention. So use ~ and not ^ in your package.json file.

**Comment by mbroadst** [comment]
@neumino the actual error itself is a rethinkdbdash error, it's not displaying the error properly, and then failing after a faulty `JSON.parse` that results in `undefined` as a result, hence the error message: `TypeError: Cannot read property 'success' of undefined`. 

Aside from that, yes as I said above thinky needs to be pegged at a version below 2.3.x.

**Comment by neumino** [comment]
Pushed 2.3.2 for the error.

**Comment by neumino** [comment]
Yep, thinky 2.2.8 should fix that.
And rethinkdbdash 2.3.2 fix the error (we were missing a return)
