### ISSUE TITLE
Pool draining before all records are inserted

### ISSUE THREAD

**Issue by kevintechie** [neumino/rethinkdbdash#246]
I have a loop that inserts about 40,000 records. After the loop is finished, I call

    r.getPoolMaster().drain();

However, the driver hasn't processed all the inserts when drain is called. This results in rejection of all the insert promises.

Is there a way to have drain() wait until all of the inserts are complete?

**Comment by neumino** [comment]
Wait for the inserts to finish before calling drain the same way you would
do with any asynchronous operations in JavaScript.
