### ISSUE TITLE
New user/password feature of RDB 2.3 is not working

### ISSUE THREAD

**Issue by meenie** [neumino/rethinkdbdash#247]
I'm using Thinky but I believe this is an issue with the driver as Thinky is passing in the user/password.  Once the options get passed to the connection code, it loses the user/password. The options being passed in [here](https://github.com/neumino/rethinkdbdash/blob/b990e525f1285a3e8adf1c2f9b4540a860fe42c1/lib/connection.js#L26), look like this:
```
{ host: 'localhost',
  port: 28015,
  db: 'my_db',
  timeout: 20,
  authKey: '',
  cursor: false,
  stream: false,
  ssl: false,
  pingInterval: -1 }
```

**Comment by meenie** [comment]
The options that thinky is passing into [here](https://github.com/neumino/thinky/blob/b0010f121603b2ff238df224cfeebaaf5560b295/lib/thinky.js#L47), look like this:
```
{ host: 'localhost',
  port: 28015,
  user: 'admin',
  password: 'foo', // Correct password I set in RDB
  db: 'my_db' }
```

**Comment by meenie** [comment]
I believe it has to do with this: https://github.com/neumino/rethinkdbdash/blob/b990e525f1285a3e8adf1c2f9b4540a860fe42c1/lib/pool.js#L22-L32

**Comment by meenie** [comment]
Okay, I believe [if I use `authKey`](https://github.com/neumino/rethinkdbdash/blob/b990e525f1285a3e8adf1c2f9b4540a860fe42c1/lib/connection.js#L35) and not `password`, it will default to the user `admin` and use the `authKey` as the password.  That's a bit convoluted...

**Comment by meenie** [comment]
Will leave this open to see if this is something you want to fix.

**Comment by neumino** [comment]
Opened https://github.com/neumino/rethinkdbdash/issues/248 since it's a driver issue.
