### ISSUE TITLE
Fetch Failed

### ISSUE THREAD

**Issue by omgj** [neumino/rethinkdbdash#256]
Trying the usual `npm install rethinkdbdash` and getting the following error:

`npm ERR! fetch failed https://registry.npmjs.org/rethinkdbdash/-/rethinkdbdash-2.3.6.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503`

Have tried on multiple routers. It's a `503` so I guess the server is being overloaded, down for maintenance etc. Any ideas? Could be a npmjs thing, but other packages install just fine.

**Comment by neumino** [comment]
Works fine for me. Ping npmjs folks if you still have this issue.
