### ISSUE TITLE
consider exporting all terms

### ISSUE THREAD

**Issue by mbroadst** [neumino/rethinkdbdash#258]
I have a need to use e.g. `r.geojson` in my code, where I don't have easy access to a passed in instance of `r`. Since the term is essentially a wrapping of the protodefs, it shouldn't be any issue to export these terms directly as part of the main entry point. Thoughts?

**Comment by mbroadst** [comment]
it looks like its easy enough to just use the drop-in approach: 
```
const r = require('rethinkdbdash')({ pool: false, cursor: true });
```

and then use the terms off of that. It is, however, an additional allocation I wouldn't otherwise need to make

**Comment by neumino** [comment]
Hum, that's not really possible because a term is tied to the instance of `r.` We use it for connections, for array limits, the default database etc.

You can use multiple instances of `r` together, but it's a bit hacky IMO.
