### ISSUE TITLE
Promise warning on `.toStream` emitting for every record

### ISSUE THREAD

**Issue by kylefarris** [neumino/rethinkdbdash#265]
I get the following message:
> Warning: a promise was created in a handler but was not returned from it

for every single document streamed out from the query when running the following query, for example:

```javascript
var fs = require('fs');
var file = fs.createWriteStream('/some/location/foo.json');
var Stringify = require('streaming-json-stringify');
r.db.table('some_data').toStream().pipe(streaming-json-stringify).pipe(file);
```

It happens in the `.toStream` method for sure--which makes sense since it's, in fact, not returning anything the promises in it's chain from what I can tell.

I'm using latest version (at the moment) 2.3.12

I tried adding `return null;` in the promise here: https://github.com/neumino/rethinkdbdash/blob/fb364a85dc8cc79d24f0d634b9bdc675795e50f9/lib/term.js#L277

No go.

I'm not super familiar with bluebird or promises in general, but, I'm developing a simple little module that allows you to stream any query out as a CSV stream (see here: https://github.com/kylefarris/rethink2csv). It actually works perfectly but I'm seeing that message in my logs and it's just cluttering it up.

Anyways, love your module, it's really quite awesome! Hope we can figure this one out!

**Comment by neumino** [comment]
Can you provide a script that I can run that produce this warning?
You could also just not print the warning by not using a dev mode.

**Comment by kylefarris** [comment]
Yeah, looking through some older issues, I can see that Bluebird is only throwing that warning to the log if `NODE_ENV` is set to `development`. But I also think I recall seeing somewhere on Bluebird's docs that you can disable this logging entirely for any particular instance of it.

In any case, things are working as they should, so, it's not the end of the world--it's just making it very hard to see the real errors in my logs while developing my app in my development environment.

If you run this exact script, you'll see the error pop up for each record:

```javascript
process.env.NODE_ENV = 'development';

var Stream = require('stream');
var r = require('rethinkdbdash')({
    pool: true,
    servers: [{host: 'localhost', port: 28015}]
});

// Some quick setup stuff
var db_name = 'empty_promises';
var table_name = 'randomness';
var random_data = [
    {first_name: 'Han', last_name: 'Solo'},
    {first_name: 'Luke', last_name: 'Skywalker'},
    {first_name: 'Chewbacca', last_name: null},
    {first_name: 'C3', last_name: 'PO'},
    {first_name: 'R2', last_name: 'D2'}
];
r.dbCreate(db_name).run(function(err, res) {
    if (err) throw err;
    if (!res.dbs_created || res.dbs_created !== 1)
        throw new Error("Oops! Couldn't create the database for testing!");

    r.db(db_name).tableCreate(table_name).run(function(err, res) {
        if (err) return cleanup(err);
        if (!res.tables_created || res.tables_created !== 1)
            return cleanup(new Error("Bummer... couldn't create the table for testing!"));

        r.db(db_name).table(table_name).insert(random_data).run(function(err, res) {
            if (err) return cleanup(err);
            if (!res.inserted || res.inserted !== random_data.length)
                return cleanup(new Error("Bummer... couldn't create the table for testing!"));
            break_promises();
        });
    })
});

function break_promises() {
    var ws = get_write_stream();
    r.db(db_name).table(table_name).orderBy('first_name').toStream().on('error', cleanup).pipe(ws).on('finish', cleanup);
}

function get_write_stream() {
    var ws = new Stream;
    ws.writable = true;
    ws.bytes = 0;

    ws.write = function(buf) {
       ws.bytes += buf.length;
    }
    ws.end = function(buf) {
       if(arguments.length) ws.write(buf);
       ws.writable = false;

       cleanup();
    }
    return ws;
}

function cleanup(other_err) {
    r.dbDrop(db_name).run(function(err, res) {
        console.log("Test data has been cleaned up!");
        if (err) throw err;
        if (other_err instanceof Error) throw err;
        process.exit(1);
    });
}
```

Hope that helps!

**Comment by neumino** [comment]
Fixed in 2.3.14

**Comment by neumino** [comment]
Thanks for the script : )

**Comment by kylefarris** [comment]
Thanks for fixing that! :-)
