### ISSUE TITLE
`cursor.eachAsync()` terminates early in v2.3.13+

### ISSUE THREAD

**Issue by marshall007** [neumino/rethinkdbdash#266]
@neumino the commit that fixed #263, 4efa6e6b8393acb7f98ed00d3340e6abd65e123b, appears to have broken `cursor.eachAsync()`. It only iterates over the first ~6k rows before mysteriously resolving. I've confirmed my code still works if I roll back to `v2.3.12`.

**Comment by neumino** [comment]
Thanks for the report @marshall007 - Fixed in 2.3.17
