### ISSUE TITLE
add socket.unref() support on connections

### ISSUE THREAD

**Issue by jonathanong** [neumino/rethinkdbdash#268]
i'd like to support `unref`ing the connections for a better graceful shutdown. specifically https://nodejs.org/api/net.html#net_socket_unref

implementation options:

- add an `.unref()` API somewhere
- expose underlying sockets via API

note that if we `unref()`, the pool should NOT create new connections

let me know how i can help. thanks

**Comment by neumino** [comment]
Hum, I'm not sure to see what's the value here.
What's wrong with `drain`?

Also what do you do with the running queries?

**Comment by jonathanong** [comment]
oh i see. didn't notice that method. will that wait until all pending queries are done before it closes the connections? if so, that's perfect.

> Also what do you do with the running queries?

that's handled elsewhere

**Comment by neumino** [comment]
Yes, `drain` waits for all pending queries to complete.
