### ISSUE TITLE
Importing rethinkdbdash? (es6 syntax error) 

### ISSUE THREAD

**Issue by donjae** [neumino/rethinkdbdash#269]
Hey, getting errors when trying to load rethinkdbdash via 'import'. Tried everything from:

`import * as r from 'rethinkdbdash/lib'`
`import r from rethinkdbdash/lib`
`import * as r from 'rethinkdbdash'`
`import r from rethinkdbdash`

Has anybody tried importing it this way and encountered issues?

**Comment by neumino** [comment]
```
import rethinkdbdash from 'rethinkdbdash';
const r = rethinkdbdash({});
```

**Comment by donjae** [comment]
Thanks, I'll definitely try that
