### ISSUE TITLE
How to force stop rethinkdbdash from trying to reconnect?

### ISSUE THREAD

**Issue by chrisabrams** [neumino/rethinkdbdash#272]
Having an issue where rethinkdbdash continually tries to reconnect, and would love a way to force it to stop trying. There is an occasion when using this with gulp and mocha where the test fails so hard that the gulp on error method never fires, and therefore the drain pool is never called.

Would it make sense in this scenario to just create a node file that loads the driver, and then calls drain?

I made a file such as the following:

```
var r = require('./src/lib/database/driver')

r.getPoolMaster().drain()

setTimeout(function() {
  process.exit()
}, 2000)
```

Is there a different approach you would recommend?

**Comment by neumino** [comment]
I'm not sure to understand what you really want.

`r.getPoolMaster().drain()` will close all the connection and the driver won't attempt to connect anymore. Is that what you are looking for?

**Comment by chrisabrams** [comment]
For anyone who comes across this issue, see https://github.com/neumino/rethinkdbdash/issues/273 for a potential solution.
