### ISSUE TITLE
A way to not create a connection when loading the driver?

### ISSUE THREAD

**Issue by chrisabrams** [neumino/rethinkdbdash#273]
I have a file called `driver.js` which looks like the following:

```
var config = require('./config').default

var r = require('rethinkdbdash')(config)

r.getPoolMaster().on('log', function() {
  //console.error.apply(console, arguments)
})

module.exports = r
```

Each time I `require` this file, a new connection is created. Is there a way to not make this happen. It makes it tough to [stop](https://github.com/neumino/rethinkdbdash/issues/272) the connection when things go crazy.

**Comment by neumino** [comment]
`require('rethinkdbdash')({pool: false})` doesn't create the pool.

Why do you think a new connection is created everytime you load the file? That's the case only if you execute different scripts.

**Comment by chrisabrams** [comment]
Try creating a script like this:

```
var r = require('rethinkdbdash')({
  servers: [
    {host: '127.0.0.1', port: 28015}
  ]
})
```

Then execute that script: you will see in the console that a connection has been made.

**Comment by neumino** [comment]
Lazily conecting doesn't have anything to do with the driver trying to reconnect when the connection is lost.

The pool is lazy by default, it just has a buffer of 50 connections. If you import the driver like this, it's what you refer as `lazyLoad: true`

```
var r = require('rethinkdbdash')({
  buffer: 0
})
```

**Comment by chrisabrams** [comment]
Ah so that is how buffer is being used. OKKK!!! Thx.
