### ISSUE TITLE
Uncatchable ReqlDriverError: Wrong Password.

### ISSUE THREAD

**Issue by julienvincent** [neumino/rethinkdbdash#274]
When an incorrect password is provided, a `ReqlDriverError` is thrown and is not caught by `_FlushErrors` and additionally does not pass through the log system so `silent: true` does not prevent this.

**Comment by neumino** [comment]
Hum, the error is properly handled as far as I can tell. It's not being propagated to process.

Connections errors are handled by the driver itself. You can access them via the `log` event, and silence the `console.error` messages by passing `silent: true` to the options.

**Comment by julienvincent** [comment]
As I said previously, `silent: true` does *not* silence this error. That is the reason for this issue

**Comment by neumino** [comment]
Works fine for me. Can you provide a script that shows your issue?

**Comment by julienvincent** [comment]
I will make a repro repo soon as I get time 👍
