### ISSUE TITLE
How to mock using rethinkdbdash

### ISSUE THREAD

**Issue by nodesocket** [neumino/rethinkdbdash#275]
Any idea how I can mock using rethinkdbdash? I have integration tests, and instead of actually inserting/selecting from RethinkDB, is it possible to have a `{ mock: true }` option which just stores and reads from memory?

**Comment by neumino** [comment]
Use a mock libraby, `rethinkdbdash` is not going to mock things.
Checkout https://github.com/neumino/reqlite if you want advanced mocks.

**Comment by aleclarson** [comment]
@neumino Do you suggest using a local `rethinkdb_data` when testing?

**Comment by neumino** [comment]
No, mocking the driver should be the way to go.

**Comment by aleclarson** [comment]
@neumino Maybe a `rethinkdbdash-mock` module should exist? Ideally, it would support `.json` files as mock tables. Or am I missing something?

**Comment by aleclarson** [comment]
@neumino Or does `rethinkdbdash` on top of `reqlite` work as expected?
