### ISSUE TITLE
Expose health of pool master

### ISSUE THREAD

**Issue by paramaggarwal** [neumino/rethinkdbdash#277]
At the moment, if a connection is lost to the database, all queries will emit errors instead of being queued. It would be nice to be able to check for the health before firing a query (so that it may otherwise be queued in memory).

I understand that the `health` event is exposed on `r.getPoolMaster()`, but it would nice to also get the health exposed as `r.getPoolMaster.getHealth()` which will simply return `this._health` from it.

(Usecase: https://github.com/paramaggarwal/emitter-rethinkdb)

**Comment by neumino** [comment]
If you do `query.run()` and get the error `None of the pools have an opened connection and failed to open a new one` it means that `_health` is false.

**Comment by paramaggarwal** [comment]
I was hoping to know that before doing `query.run()`! 😄

**Comment by grantcarthew** [comment]
I agree with @paramaggarwal. It would be great to have `.getHealth()` @neumino.
I can raise a PR if you like.

**Comment by neumino** [comment]
I'm not convinced that you need this. Health can be true and your query can fail. Health being true doesn't mean that a connection is available (at start time it just means that we didn't fail to open a connection).

**Comment by grantcarthew** [comment]
Hi Michel, I was interested because I am creating a driver and destroying it after a quick test. This is causing an error in testing that will probably never happen in production. Maybe I should add a small delay.

Example is here: https://github.com/grantcarthew/node-rethinkdb-job-queue/blob/master/tests/queue.spec.js#L284-L305
