### ISSUE TITLE
Option to continue queuing requests while reconnecting

### ISSUE THREAD

**Issue by paramaggarwal** [neumino/rethinkdbdash#278]
At the moment if connection to the database is lost, all queries will immediately start failing. If there was an option to continue queuing requests while the health is bad, it would help avoid losing queries.

The driver already has an in-memory queuing mechanism, so it would make sense to use it instead of the application having to maintain a separate queue. This also makes it more resilient to momentary failures.

(Usecase: https://github.com/paramaggarwal/emitter-rethinkdb)

**Comment by neumino** [comment]
Hum, why would you want that?

If your database goes down, it means that your clients will pile a bunch of request and your job will eventually be OOMed. You don't really want a cascade of failures in case only your database goes down.

**Comment by paramaggarwal** [comment]
That's right, thanks @neumino.
