### ISSUE TITLE
Connection

### ISSUE THREAD

**Issue by minimok** [neumino/rethinkdbdash#281]
So I start my node.js server. The first thing I need to do is "attempt" a connection to the RethinkDb database. 
1. If I do not succeed, I need to know immediately that the connection attempt errored out.
2. If I do succeed, I need to know immediately.
3. If I do succeed, I need to know immediately if the connection is lost at any time in the future.

This is "Database driver 101" stuff. Does your utility manage it? If so....how?? (It really should be documented "Front and Center")

**Comment by neumino** [comment]
Not sure what you are looking for. If by a connection you mean the status of your pool, then it's documented here:
https://github.com/neumino/rethinkdbdash#advanced-details-about-the-pool

If you want to manually open a connection, then you can just use `r.connect`.
