### ISSUE TITLE
Replace with null returns no changes

### ISSUE THREAD

**Issue by MarkHerhold** [neumino/rethinkdbdash#284]
I am having an issue where conditionally replacing a document with null (deleting it) returns `undefined` every time, despite including `{ returnChanges: true }`.

```js
var result = yield Model // this is actually a Thinky model but I don't think it matters
    .get(id)
    .replace(function(thing) {
        return r.branch(
                r.branch(thing('color').ne('green'),
                r.error('Object color must be green to be deleted'),
                null // delete the document
        )
    }),
    { returnChanges: true }
)

// result will be undefined
```

I think this may have to do with some magic rethinkdbdash is doing under the hood, but I really am not sure.

Possibly related: http://stackoverflow.com/questions/39308386/conditional-delete-in-rethinkdb

Any help would be greatly appreciated.

**Comment by neumino** [comment]
This is because of Thinky. If you don't use Model or use execute instead of
run, you'll see the change.

**Comment by MarkHerhold** [comment]
Thanks for the response!

Unfortunately, I still can't seem to get anything despite trying both `.run()` and `.execute()`. I should be able to get the deleted model back if I use `.run()`, correct? The docs seem to indicate I should.

Here's an executable example.

```
const thinky = require('thinky')();
const type = thinky.type;
const r = thinky.r;

var Thing = thinky.createModel("things", {
    id: type.string(),
    color: type.string()
});

var document = new Thing({
    color: 'green'
});

document.save().then(function(obj) {
    console.log('created obj ' + obj.id);
    return obj.id;
}).then(function(id) {
    return Thing
        .get(id)
        .replace(function (thing) {
            return r.branch(thing('color').ne('green'), r.error('Object color must be green to be deleted'), null)
        }, { returnChanges: true })
        .execute(); // as per suggestion, tried .run() as well
}).then(function (thing) {
    console.log('got', thing); // <--- thing is always undefined
});
```
