### ISSUE TITLE
Crash on Ubuntu 14.04.5

### ISSUE THREAD

**Issue by wacky6** [neumino/rethinkdbdash#294]
Error message:

```Text
> FATAL ERROR: node::PBKDF2() Out of Memory
 1: node::Abort() [node]
 2: 0x10b67bc [node]
 3: 0x10bb209 [node]
 4: node::crypto::PBKDF2(v8::FunctionCallbackInfo<v8::Value> const&) [node]
 5: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [node]
 6: 0x9f6702 [node]
 7: 0x9f6d7e [node]
 8: 0x1f15d27092a7
```

The code that cause this problem:
```JavaScript
const r = require('rethinkdbdash')()
```

Environment:

* Ubuntu 14.04.5 x64
* Node v6.6.0, built from source
* npm 3.10.3
* rethinkdbdash 2.3.23
* rethinkdb 2.3.5, from official ubuntu repository

rethinkdbdash v2.2, v2.1 do not have this problem.

How to verify:

1. Get Ubuntu
2. Install, configure, start rethinkdb instance
3. cd into a directory (eg: `cd /tmp`)
4. npm i rethinkdbdash@2.3
5. node -e 'require("rethinkdbdash")()'

**Comment by scttcper** [comment]
Same as #293. Use node v6.5.0 until fixed.
