### ISSUE TITLE
How to catch connection errors?

### ISSUE THREAD

**Issue by maximilian-krauss** [neumino/rethinkdbdash#295]
Hi,
I'm trying to use the rethinkdbdash driver with an express app. As long as the database connection details are correct all works pretty well. But as soon as the password is wrong (for example) the whole connection crashes and it does not invokes the catch method from the promise it returns.
How do I catch these errors?

I put together a little example on how you can reproduce the behavior:

```
'use strict';

let r = require('rethinkdbdash')({
  pool: true,
  db: 'this-db-exists',
  user: 'admin',
  silent: true,
  password: 'i-am-wrong',
  servers: [{
    host: '192.168.xx.xxx',
    port: 28015
  }]
});

r.table('content')
  .getAll()
  .run()
  .then(function(results) {
    console.log(results);
  })
  .catch(function(err) {
    console.log('oh no, i do not get called :-(');
  });

/* This is what it prints out in the console
Unhandled rejection ReqlDriverError: Error 12:Wrong password.
    at Socket.<anonymous> (/Users/max/test/rdbdash/node_modules/rethinkdbdash/lib/connection.js:176:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:536:20)
*/
```

node: 4.5
rethinkdbdash: 2.3.23

Regards,
Max

**Comment by neumino** [comment]
Sorry, missed that issue.

The short answer is you can't catch this specific error though it shouldn't be an unhanded error.

**Comment by neumino** [comment]
(that is to say it's a bug, the error in your catch should be something like no pools have available connections and we failed to open one)
