### ISSUE TITLE
Error: write after end

### ISSUE THREAD

**Issue by chattes** [neumino/rethinkdbdash#296]
Hi,
we are using RethinkDBdash as our rethinkDB driver along with Nodejs. Its working great. But i started a bit of stress testing on my dev machine, and when I send 500+ concurrent requsts per second, the server is crashing with the following error:

events.js:160
      throw er; // Unhandled 'error' event
      ^

```
Error: write after end
    at writeAfterEnd (_stream_writable.js:166:12)
    at Socket.Writable.write (_stream_writable.js:217:5)
    at Socket.write (net.js:651:40)
    at Connection._sendProof (/home/chattes/dev/LocationTracker/prototype/node_modules/rethinkdbdash/lib/connection.js:281:19)
    at Connection._computeSaltedPassword (/home/chattes/dev/LocationTracker/prototype/node_modules/rethinkdbdash/lib/connection.js:247:10)
    at Socket.<anonymous> (/home/chattes/dev/LocationTracker/prototype/node_modules/rethinkdbdash/lib/connection.js:184:18)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
```

We are using Node 6.5.0 and "rethinkdbdash": "^2.3.23"
Request you to kindly help with the same.

Thanks

**Comment by neumino** [comment]
My guess is that you're hitting your max open files limit and can't properly open connections after that. Looking at the stacktrace, it's probably a bug introduced with the new handshake, 2.2.x should work for now.

It should be relatively straightforward to fix.

**Comment by chattes** [comment]
Okay let me try out with 2.2.x. I will keep you posted. although i increased my max pool to 10000 after your suggestion and it disappeared for a while. But it has come back again today.

Thanks

**Comment by chattes** [comment]
Hi quick question this error 'Fail to create a new connection for the connection pool. Error:{"message":"Failed to connect to localhost:28015 in less than 20s.","isOperational":true}'
Will it try and create connections once sockets are available again?

**Comment by chrisabrams** [comment]
@neumino any updates on this? I'm getting the exact same error. I only started getting this once the number of connections per second increased. The connection is made, and then after a few seconds it is lost, and no new connections can seem to be made.

```
Fail to create a new connection for the connection pool. Error:{"msg":"Failed to connect to cluster.local:28015 in less than 5s","message":"Failed to connect to cluster.local:28015 in less than 5s.","isOperational":true}
```

Here is my driver file:

driver.js
```
const driverConfig = {
  authKey: process.env.RETHINK_DB_AUTH_KEY || '',
  buffer:  process.env.NODE_ENV === 'production' ? 50 : 3,
  db:      process.env.RETHINK_DB_NAME,
  host:    process.env.RETHINK_DB_HOST || 'localhost',
  min:     process.env.NODE_ENV === 'production' ? 50 : 3,
  pool:    true,
  port:    process.env.RETHINK_DB_PORT || 28015,
  timeout: process.env.RETHINK_DB_DRIVER_TIMEOUT || 5
}
const r = require('rethinkdbdash')(driverConfig)
module.exports = r
```

**Comment by chrisabrams** [comment]
I changed my driver config to:

```
const driverConfig = {
  authKey: process.env.RETHINK_DB_AUTH_KEY || '',
  buffer:  process.env.RETHINK_DB_DRIVER_BUFFER || 50,
  db:      process.env.RETHINK_DB_NAME,
  host:    process.env.RETHINK_DB_HOST || 'localhost',
  pool:    true,
  port:    process.env.RETHINK_DB_PORT || 28015,
  timeout: process.env.RETHINK_DB_DRIVER_TIMEOUT || 20,
  timeoutGb: process.env.RETHINK_DB_DRIVER_TIMEOUTGB || 60 * 60 * 1000
}
```

And the issue has gone away for the moment.
