### ISSUE TITLE
What is the general approach for passing the "r" instance around

### ISSUE THREAD

**Issue by marchaos** [neumino/rethinkdbdash#297]
Hey, 

I've started to use rethinkdbdash in a small project, but I have multiple files that all require database access. Using the official library, I was passing the "conn" object everywhere. I've found with rethinkdbdash I need to pass the "r" instance around everywhere, as it's used to construct a pool like so:

var r = require('rethinkdbdash')({
    db: 'mydb'
});

If I need access in another class or file, I need to pass this instance around. Is there a way to require('r') and get the a global instance, or is what I'm currently doing the preferred approach?

**Comment by neumino** [comment]
```
// r.js
var r = require('rethinkdbdash')()
module.export = r;
```

```
var r = require('r.js');
```

**Comment by marchaos** [comment]
Um, why didn't I think of that :)
