### ISSUE TITLE
close/drain an specific connection

### ISSUE THREAD

**Issue by luisyonaldo** [neumino/rethinkdbdash#298]
Is there a way to close an specific connection from the pool and not drain all the connections? E.g.:
```javascript
r.getPoolMaster().drain(<pool_coonection>);
```

I need to cancel some query if the server memory pass some limit, so I need to cancel the current query (can also cancel all the connections but I would prefer just close that connection) and run it again later in the future (after some defined time).

This an example of what I'm trying to do:
```javascript
setInterval(function () {
  mem = getServerMem();
  if (mem < limit - delta && running) {
    query.run();
    running = true;
  }
  if (mem >= limit && !running) {
    query.drain();
    runing = false;
  }
}, 1000);
```

**Comment by neumino** [comment]
Hum, in this case you can't just use `run`. You need to get a connection by opening yourself of calling `r.getPoolMaster().getConnection()` and then manually closing it if you want to kill the query.
