### ISSUE TITLE
ISO8601 working okay?

### ISSUE THREAD

**Issue by sjmcdowall** [neumino/rethinkdbdash#299]
Maybe I am overthinking this -- but I am using rethinkdbdash -- and I am inserting some new rows from some outside data that has dates in ISO8601 string format.  So -- I think I need them to convert to rethingDB format and am trying to do something like 
body.timeStamp = r.ISO8601(body.timeStamp) ;   

However, it's throwing a stack trace error : 
```
   throw new Error.ReqlDriverError('`'+method+'` takes '+num+' argument'+((num>1)?'s':'')+', '+args.length+' provided', term._query);
    ^
ReqlDriverError: `toJSON` takes 0 argument, 1 provided after:
r.ISO8601("2016-09-29T19:32:11.888Z")
    at Term._arity (/Users/sjm/work/galaxy/next-gen/us-tems/services/us-tems-worker/node_modules/rethinkdbdash/lib/term.js:3016:11)
    at Term.toJsonString (/Users/sjm/work/galaxy/next-gen/us-tems/services/us-tems-worker/node_modules/rethinkdbdash/lib/term.js:2767:10)
    at Object.stringify (native)
```

I looked in the RethinkDB documentation .. which clearly shows you are supposed to give it a ISO8601 string to convert to internal UTC seconds thing?  

r.ISO8601("2013-08-09T18:53:15.012-07:00") 

in https://www.rethinkdb.com/docs/dates-and-times/javascript/

And the same command runs fine in the Data Explorer:

r.ISO8601("2016-09-29T19:32:11.888Z")

```
1 row returned in <1ms.
value
1
Thu Sep 29 2016 19:32:11 GMT+00:00
```

So pretty lost as to what to do here... 

Cheers!

**Comment by neumino** [comment]
That's because you try to call `JSON.stringify(r.ISO(...))`. You can't stringify a ReQL term.

**Comment by sjmcdowall** [comment]
Well that solved the issue alright -- and I NEVER EVER would have guess I could not JSON.stringify a ReQL term!  Ever!  :)
