### ISSUE TITLE
"The connection was closed by the other party" error

### ISSUE THREAD

**Issue by marchaos** [neumino/rethinkdbdash#300]
Hey, 

I'm seeing this error - "The connection was closed by the other party", which looks like this one - https://github.com/neumino/rethinkdbdash/issues/192. I added ping interval "5", but I still get this error. I'm on OS X with version 2.3.23 of rethinkdbdash.

If I stop rethinkdb and then restart it, on "healthy" I perform another query and I get this error.

**Comment by neumino** [comment]
How do you stop/restart rethinkdb?
How long do you wait?

**Comment by cadrogui** [comment]
Hi, i have the same issue, my rethinkdn server is on a VM on Virtualbox in a Debian Machine, i have 5 docker containers that perform tasks over the rethinkdb server but suddenly i got this error and all mi microservices cant perform any task because this error, what can i do for fix this?

there is a way to do an shared pool resource for rethinkdb for all my microservices?

regards

**Comment by neumino** [comment]
Hum, my guess is that Virtualbox or docker is killing the connection without properly passing a FIN packet. As far as I know, docker works fine, but I heard a few person having issues with Virtualbox and TCP connections.

**Comment by cadrogui** [comment]
Hi, ive change the RethinkDB machine from Virtualbox to Parallels on clean install, and i have the same issue....

**Comment by neumino** [comment]
Can you try without a VM?

**Comment by cadrogui** [comment]
ok, ill install rethink on my mac os host machine.

**Comment by cadrogui** [comment]
same issue, and get The connection was closed before the query could be completed for....

**Comment by joakimbeng** [comment]
Same issue here! I'm running RethinkDB on my host machine (which is a Mac) and then connect to it from Docker containers

**Comment by neumino** [comment]
That's a bit of an old issue. My guess is that something in your stack doesn't keep the TCP connection open.

You can try with a simple dump TCP connection (`net.connect()` and see if the connection dies after some time
