### ISSUE TITLE
accounts problems on discovery and wrong password problem.

### ISSUE THREAD

**Issue by goors** [neumino/rethinkdbdash#301]
From few days ago I am getting error over all my servers like:
`
{ error: 'Wrong password', error_code: 12, success: false }`

When I add new user and grant permissions this part of driver:

```
if (options.user === undefined) {
      this.user = r._user;
    } else {
      this.user = options.user;
    }
```

is completely ignore and self.user is always admin (but i put options.user = "myusername").

If discovery is set to true and user is different from "admin" i am getting of course error regarding server_status.

So as far as I can see it some huge problems and no solution!

**Comment by neumino** [comment]
What's the stacktrace? Code snippet?
Discovery is using the server_status table. Does your user have access to that table?

**Comment by goors** [comment]
@neumino only admin user has access to server_status. But I give up on your driver since it causing port flooding.
