### ISSUE TITLE
DeprecationWarning - Buffer in node v7

### ISSUE THREAD

**Issue by alexchepura** [neumino/rethinkdbdash#304]
Node v7 from https://nodejs.org/download/test/
To see the tracing `node --trace-deprecation server`

```
DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.
    at Buffer (buffer.js:79:13)
    at Connection._sendProof (/www/node_modules/rethinkdbdash/lib/connection.js:281:40)
    at InternalFieldObject.ondone (/www/node_modules/rethinkdbdash/lib/connection.js:255:12)
```

**Comment by chrisvariety** [comment]
See also https://github.com/rethinkdb/rethinkdb/pull/6144

**Comment by jtlapp** [comment]
I get this is v7.1.0, which is the latest stable. Do we have to wait for 8.0.0 for the fix? Thanks!

**Comment by neumino** [comment]
What version of rethinkdbdash are you using?

**Comment by jtlapp** [comment]
Oops, looks like I left my comment on the wrong repo. Sorry, I meant to ask that of the node guys.

**Comment by krishangupta** [comment]
I still get this in 7.2. Anyone else?

**Comment by neumino** [comment]
What version of rethinkdbdash are you using?

**Comment by krishangupta** [comment]
@neumino my mistake - I thought this was a forum about node. It was the first result on Google so I just assumed. Thanks for replying!
