### ISSUE TITLE
drivers keeps connecting to old ips that does not exists in config anymore?

### ISSUE THREAD

**Issue by goors** [neumino/rethinkdbdash#308]
```
var servers =[ {

    host: "h1",
    port: config.get('rethinkDB.port'),
    }, 
    {
    host: "h2",
    port: config.get('rethinkDB.port'),
    }
]
```

now when i remove host: "h2", from config (meaning there is no host h2) driver keeps trying to connect to h2 host!

Giving me some message like this:

> Fail to create a new connection for the connection pool. Error:{"msg":"Failed to connect to h2:28015\nFull error:\n{\"code\":\"ENETUNREACH\",\"errno\":\"ENETUNREACH\",\"syscall\":\"connect\",\"address\":\"h2\",\"port\":28015}","message":"Failed to connect to h2:28015\nFull error:\n{\"code\":\"ENETUNREACH\",\"errno\":\"ENETUNREACH\",\"syscall\":\"connect\",\"address\":\"h2\",\"port\":28015}.","isOperational":true}

**Comment by neumino** [comment]
Do you use `discover: true`?

**Comment by goors** [comment]
Yes I do, I use `discover: true`.

**Comment by neumino** [comment]
It seems to work fine for me.

Can you provide the full config of rethinkdbdash?
How do you remove the server?
Are the servers still on the web-ui? Do they host data? What does `r.db('rethinkdb').table('server_config')` and `r.db('rethinkdb').table('server_status')` return?
