### ISSUE TITLE
Not returning or erroring from the promise

### ISSUE THREAD

**Issue by charandas** [neumino/rethinkdbdash#315]
I lifted this code from a [tutorial](https://docs.feathersjs.com/databases/rethinkdb.html) and am really new to `rethinkdb` in general. My long night of debugging here has not revealed much, except that `adapter.dbCreate('feathers')` is definitely called (although with no effect on the database - which is running in compose.io), and returns some sort of enormous object.

It makes me think that the first `run` is happening, but why is usual promise-chaining not working, I have no clue.

```js
// adapter is simply r or rethinkdbdash instance created with require('rethinkdbdash')(options)
function initSurvey(adapter) {
	logger.info('Initializing database');
	// Create your database if it doesn't exist.
	return adapter
		.dbList()
		.contains('feathers')
		.do(dbExists => adapter.branch(dbExists, { created: 0 }, adapter.dbCreate('feathers')))
		.run()
		.then(() => {
			// Never executed, nor do any catch/error if I add them to the above run
			logger.info('Initializing survey table');
			adapter
				.db('feathers')
				.tableList()
				.contains('surveys')
				.do(tableExists => adapter.branch(tableExists, { created: 0 }, adapter.tableCreate('surveys')))
				.run()
				.error((error) => {
					logger.error(error);
					throw error;
				});
		});
}
```

I would appreciate any help. Thanks for making an awesome plugin with promise-support!

**Comment by charandas** [comment]
So as it turned out it was the connection to gcp/compose rethinkdb. When I installed `rethinkdb` locally on my macOS machine, I am able to run with promises/rethinkdbdash.

I wonder why I never got any errors thrown by `rethinkdbdash` for the compose.io configuration.

Willing to throw my configuration here so the mystery can be resolved:

```
"user": "admin",
"password": "xT9rUFR7fYY-D5Jqqpv7XNMdNmELMyo9Yk-bmxoKNqI",
"host": "gcp-us-east1-cpu0.dblayer.com",
"port": 15316,
"options.ssl.ca": [compose.pem.txt](https://github.com/neumino/rethinkdbdash/files/637825/compose.pem.txt) // nested key shown in 1 line for simplicity
```

**Comment by charandas** [comment]
Much `console.log` type debugging showed that it was the `getConnection` on pool master, that although it saw a healthy pool of 1 would not do much after this step:

```else {
    // All pool are busy, buffer the request
    return new Promise(function(resolve, reject) {
      self._line.push({
        resolve: resolve,
        reject: reject
      });

      self.emit('queueing', self._line.getLength())```

So the caller of this function (`term.js`) never had a `then` or `catch/error` produce anything on the `getConnection` call, and the node process simply existed silently. Very interested in what's up.

**Comment by neumino** [comment]
You're not catching the error in your first query
```
adapter
		.dbList()
		.contains('feathers')
		.do(dbExists => adapter.branch(dbExists, { created: 0 }, adapter.dbCreate('feathers')))
		.run()
		.then(() => { ... }
                .error( (e) => console.log(e) )

**Comment by charandas** [comment]
@neumino Thanks for taking a look. I omitted some stuff above for brevity.

This comment was my way of telling, I cannot catch on the first query either.

>// Never executed, nor do any catch/error if I add them to the above run

Would you have any other suggestions as to places to look? Automatic connection handling is great, but in my case, I want to debug what's going on, and a silent process exit is not helping.

**Comment by neumino** [comment]
Can you provide a full script that triggers this behavior then?

**Comment by charandas** [comment]
@neumino here you go: https://github.com/charandas/rethinkdbdash_test

**Comment by charandas** [comment]
Think I found the problem: my loadash set for caCert is actually a noop. Why won't the driver complain though?

**Comment by charandas** [comment]
I actually meant `set(options, 'ssl.ca', [caCert]);`, but wrote `set('options.ssl.ca', [caCert]);`. Sorry for filling a false report. But either way, a thrown error would be useful in this case.

**Comment by neumino** [comment]
That's a question for the loadash folks.

**Comment by charandas** [comment]
@neumino if I totally don't touch lodash, and simply omit `ssl.ca` setting, I see the above behavior.

So no errors thrown. Thoughts?

**Comment by neumino** [comment]
If the driver cannot connect, all the query you'll try to run will return an error.

RethinkDB doesn't require ssl to work, so not providing a certificate in the driver config is a valid thing to do.

**Comment by charandas** [comment]
My queries just silently fail. The promise's then,error, and catch never return.

**Comment by neumino** [comment]
Add `timeout: 1` in the option. I'm pretty sure that your query is not being run because you are not connected to your RethinkDB instance.
