### ISSUE TITLE
One connection pool

### ISSUE THREAD

**Issue by chrisabrams** [neumino/rethinkdbdash#317]
Is it possible to just have one connection pool? Every file that I have that requires a file containing `rethinkdbdash` results in new connection pool. Sometimes I have a single test that ends up like this:

```
Creating a pool connected to localhost:28016
Creating a pool connected to localhost:28016
Creating a pool connected to localhost:28016
Creating a pool connected to localhost:28016
Creating a pool connected to localhost:28016
Creating a pool connected to localhost:28016
Creating a pool connected to localhost:28016
Creating a pool connected to localhost:28016
Creating a pool connected to localhost:28016
Creating a pool connected to localhost:28016
Creating a pool connected to localhost:28016
Creating a pool connected to localhost:28016
Creating a pool connected to localhost:28016
Creating a pool connected to localhost:28016
Creating a pool connected to localhost:28016
Creating a pool connected to localhost:28016
```

How do you tell the driver to just keep the same pool instead of making new ones?

**Comment by marshall007** [comment]
@chrisabrams no, there's no way to share a connection pool across multiple instances. You'll need to create a single instance and reference it across your entire application, as opposed to requiring `rethinkdbdash` separately in each file.
