### ISSUE TITLE
Yielding a query with async/await

### ISSUE THREAD

**Issue by migueloller** [neumino/rethinkdbdash#318]
With regards to: https://github.com/neumino/rethinkdbdash#optional-run-with-yield

Since Babel transforms `async/await` to generators, awaited promises are yielded, which in turn causes the queries to run when using async functions even if `run()` isn't called.

Is this expected behavior? Can you use `await` interchangeably with `yield` or is this a side effect due to Babel using generators behind the scenes to implement `async/await`. Once `async/await` is fully supported in Node, will `await` stop working?

**Comment by neumino** [comment]
You can use the option optionalRun: false if you don't want this behavior.

**Comment by migueloller** [comment]
@neumino, thanks for the super fast reply!

I find the behavior convenient. I just wanted to understand the initial motivation to make sure that I check the edge cases of relying on Babel to use generators behind the scenes. 😄 

Does `Term` only respond to `yield`s or is it thenable?

**Comment by neumino** [comment]
The initial motivation is that you can write `yield query` instead of `yield query.run()`. Then the option to remove this behavior was added because babel added these new async/await features.

**Comment by migueloller** [comment]
@neumino,

Sounds good! Do you think that this should be documented so that other people can avoid the confusion in the future? Perhaps it can be right after the optional yield run section in the README?

Something like: "This feature is intended to be used with the `yield` keyword only. Since Babel transforms async/await into generators then the same will happen for the `await` keyword. Keep in mind it's only a side effect and not designed this way. The `optionalRun` will disable this behavior if needed."

**Comment by marshall007** [comment]
@migueloller it's not necessarily specific to the `yield` keyword. `Term` is a thenable, so you can return a query from within a promise chain (without explicitly calling `.run()`) and it will execute the query.

**Comment by migueloller** [comment]
@marshall007,

> `Term` is a thenable

Awesome! This is exactly what I was wondering. Thanks for the response. 😄
