### ISSUE TITLE
"Creating a pool" log message should not be an error

### ISSUE THREAD

**Issue by Nogbit** [neumino/rethinkdbdash#320]
There are many ways to solve this, I do see that I can pass in my own logger but it's an all or nothing in this module with no way to decipher as a consumer if a message is error or not.  The `Creating a pool connected to [server]` message should not be [logged](https://github.com/neumino/rethinkdbdash/blob/f77d2ffb77a8c0fa41aabc511d74aa86ea1136d9/lib/pool.js#L64) as an [error](https://github.com/neumino/rethinkdbdash/blob/f77d2ffb77a8c0fa41aabc511d74aa86ea1136d9/lib/helper.js#L10)

The alternative is that everything is silent and instead it would be nice if actual errors get logged and info messages (connection pool created) getting logged as something else.  Something that can take in a more intelligent logger with different log levels being implemented in this module.

**Comment by neumino** [comment]
You can pass your own logger if you don't want things to be logged in STDERR
https://github.com/neumino/rethinkdbdash#connection-pool

If you log successful connections to STDOUT, and disconnections to STDERR, then you need to look at both logs to know the state of your pool (connected or not). If they are dumped in two different files, this is a pain to do.

**Comment by Nogbit** [comment]
Crossing my fingers for https://github.com/neumino/rethinkdbdash/pull/355
