### ISSUE TITLE
You can't open a pool and then immediately drain it without flooding the console with errors

### ISSUE THREAD

**Issue by ralphholzmann** [neumino/rethinkdbdash#328]
If you follow the instructions [here](http://thinky.io/documentation/architecture/) on importing thinky, and then execute the following code:

```js
import { thinky } from 'database';

thinky.r.getPoolMaster().drain();
```

Your console will be flooded with `None of the pools have an opened connection and failed to open a new one`

This is because you start draining pools before all the connections to said pools are established. It ends up hitting `PoolMaster.getConnection` while draining, and then you get one of these errors for each outstanding unestablished connection in the queue.

You might ask why you would want to do this? We have a couple of scripts that we run throughout the day to populate our database, and based on certain conditions (time of day, current date), those scripts might actually not end up doing any work. In these cases, we open up a pool and then immediately close it.

These errors rack up several gigs of logs in our server after a few days, so anything that can be done to mitigate it would be much appreciated.

Thanks for all your work here!

**Comment by neumino** [comment]
All the thinky options are passed to rethinkdbdash, so you can pass `silent: true` if you want and listen to the `log` event.

Alternatively, you can import the module only when you need it.

**Comment by withinboredom** [comment]
Just throwing this out there: afaik, there's no way to conditionally `import` in es6. I'm running into this issue as well when unit tests pass too quickly in a library I'm working on.

**Comment by ralphholzmann** [comment]
@neumino unfortunately the `silent` flag doesn't suppress this error -- ill keep digging.

**Comment by ralphholzmann** [comment]
Gonna see if I can write a patch to kill this once and for all
