### ISSUE TITLE
The pool does not have any opened connections and failed to open a new one.

### ISSUE THREAD

**Issue by nickpoorman** [neumino/rethinkdbdash#34]
Currently, there seems to be a memory leak problem with rethinkdb, which is causing it to crash and gives me a unique opportunity to see what happens to the pool when the database goes down.

Every time rethinkdb crashes and restarts, the pool doesn't seem to ever reconnect, --even after rethinkdb has been restarted. All I get are these errors: `ReqlDriverError: The pool does not have any opened connections and failed to open a new one.`

**Comment by ArkeologeN** [comment]
```
Failed to connect to 172.17.0.1:28015 in less than 20s.
ReqlDriverError: Failed to connect to 172.17.0.1:28015 in less than 20s.
    at null._onTimeout (/private/var/www/etc/wynk/node_modules/thinky/node_modules/rethinkdbdash/lib/connection.js:49:12)
    at Timer.listOnTimeout (timers.js:110:15)
Possibly unhandled ReqlDriverError: None of the pools have an opened connection and failed to open a new one.
```

I'm using rethinkdb >= 2.0.6

**Comment by neumino** [comment]
This doesn't mean it's a bug in rethinkdbdash.

Try to connect with the official driver to `172.17.0.1:28015`. I'm not aware in rethinkdbdash of any bug at the moment.

My guess is that you didn't properly set your container/firewall/rethinkdb.

**Comment by ArkeologeN** [comment]
`docker run -d rethinkdb` --> it does `bind --all` to expose the containers. 

PS: I just fixed the issue. The port was exposed on IPv6 and not v4 of the container. Not sure why :)
