### ISSUE TITLE
how to use r.getPoolMaster().on('healthy' with a rethinkdb-proxy

### ISSUE THREAD

**Issue by mariosouto** [neumino/rethinkdbdash#353]
Hi!

I'm using RethinkDB feeds with a NodeJS application in order to keep track on the changes in the database.

When RethinkDB goes down i use

```
r.getPoolMaster().on('healthy'
```

to keep track if RethinkDB is alive or not, and rejoin the feeds.

This works just fine. When RethinkDB goes down it emits a healthy event with the value of false and another one with the value of true when it goes up.

But now i need to use a RethinkDB-Proxy in front of my RethinkDB instance and i'm making my Node app connect to the Proxy. The problem is that when i use a Proxy and RethinkDB goes down, it's not emitting the healthy event or at least i don't get it bc i'm connected to the Proxy.

Is there a way to make the Proxy emit this event? Or to capture it from my instance? Or any other possible approach?

Hope i was clear enough

Thanks!

**Comment by neumino** [comment]
Hum, what happens if:
- You have a changefeed connected to RethinkDB via the proxy
- Kill RethinkDB
- Restart RethinkDB
- Does the feed still work in this case?

**Comment by mariosouto** [comment]
@neumino I'll try this out and let you know

**Comment by mariosouto** [comment]
@neumino Nope, it doesn't. Also it doesn't emit the `healthy` event 😕 . If i do this directly to the DB works like a charm but it's not the same with the proxy

**Comment by neumino** [comment]
Hum yea that what I thought would happen.

The healthy event is based on the connection itself. Since the connection to the proxy is always fine the driver things that everything works fine. That's a bug in how the RethinkDB proxy doesn't properly propagate the error upstream

**Comment by mariosouto** [comment]
I'm closing this bc seems to be more a RethinkDB issue. Thanks for the help anyway
