### ISSUE TITLE
ReqlDriverError: None of the pools have an opened connection and failed to open a new one

### ISSUE THREAD

**Issue by GeoffreyPlitt** [neumino/rethinkdbdash#359]
We continue to see the error above while using this driver, yet our RethinkDB hosting company does not see any of these connection attempts in their logs, and our app infrastructure (Heroku) also does not see failed connections.

Assuming my database really is reachable and ready to receive connections, why else could this error be happening?

**Comment by aleclarson** [comment]
Could be a firewall issue. Does Heroku have anything like that?

**Comment by GeoffreyPlitt** [comment]
No. But my new guess is that we were saturating outgoing socket limits. I think I had 5-10 instances of the driver, each with 10 outgoing connections, so it might have been over 100 outgoing connections and hit a limit. I'll close this for now.

**Comment by mxstbr** [comment]
I'm running into this, this error has been crashing our production server for the past couple weeks. We've tried limiting the pool size, but it's still happening.

Did you manage to resolve this @GeoffreyPlitt?

**Comment by GeoffreyPlitt** [comment]
@mxstbr For me, it was most likely a limit on outgoing socket connections. My server was a Heroku dyno, and I think I was saturating the resource limits. So not a rethinkdb driver problem, more of a misunderstanding of OS limits.
