### ISSUE TITLE
Expose original conn variable to client

### ISSUE THREAD

**Issue by PassTheMayo** [neumino/rethinkdbdash#362]
It would be very helpful if you could add the original `conn` to the RethinkDB client? It would allow people to assign their own events to it, including the `close` event.

**Comment by neumino** [comment]
Hum, I think there's a misunderstanding on how connections are used.

Connections are created/reused/closed as needed, there's a pool of connections, not a single one. There's also no need to listen to a specific connection. The driver already takes care of that.
