### ISSUE TITLE
Cant import module using es6

### ISSUE THREAD

**Issue by nigel-dewar** [neumino/rethinkdbdash#369]
Hi There,

I found the module wont import when using es6. For instance, this does not work

 import * as r from 'rethinkdbdash';

or  import rethinkdbdash from 'rethinkdbdash';

throws an error. Im using typescript, targeting es 6.

![image](https://user-images.githubusercontent.com/9402456/36123845-baaa35cc-1099-11e8-95aa-c304af6607b0.png)

have also tried this

![image](https://user-images.githubusercontent.com/9402456/36123929-1181deae-109a-11e8-9183-9b6c2d5400a7.png)

but it throws this error

![image](https://user-images.githubusercontent.com/9402456/36123954-24d66010-109a-11e8-9bb5-d839665062cb.png)

this of course still works fine
 const r = require('rethinkdbdash')({db: 'CRMv3', silent: true});

Any help would be greatly appreciated, as I do really love your driver. Its really nice to work with.

cheers

Nige

**Comment by sagivf** [comment]
Hey @nigel-dewar, I just tired this on a project and it worked fine. There are no TS definitions for rethinkdbdash so it's probably some sort of TS config, or maybe adding an "any" somewhere.
If you can recreate the issues on some github project I don't mind trying it out to help.

**Comment by nigel-dewar** [comment]
You are right sorry. Adding an any solved it. My bad.
