### ISSUE TITLE
Drain promise resolution

### ISSUE THREAD

**Issue by cedbale** [neumino/rethinkdbdash#372]
Hello,

I would like to handle some post action **after** connection has been drain. After a look into the code, it seems that drain return a promise but i have difficulties to understand when the promise is resolved. By the way it seems that the promise is never resolved. 

Is there a possibility to implement an async action like below ?

```
rdb.getPoolMaster()
        .drain()
        .then(() => {
            console.log('RDB drained');
        })
```

**Comment by neumino** [comment]
That should work as far as I know
https://github.com/neumino/rethinkdbdash/blob/master/long_test/discovery.js#L407
