### ISSUE TITLE
Fail to create a new connection on node v.8.10

### ISSUE THREAD

**Issue by simpleseeker** [neumino/rethinkdbdash#383]
I have a rethinkdbdash test script that works fine under node v.6.10.3, but gets the below error under node v.8.10.0

Fail to create a new connection for the connection pool. Error:{"msg":"Could not parse the message sent by the server : 'ERROR: Received an unsupported protocol version. This port is for RethinkDB queries. Does your client driver version not match the server?\n'","message":"Could not parse the message sent by the server : 'ERROR: Received an unsupported protocol version. This port is for RethinkDB queries. Does your client driver version not match the server?\n'.","isOperational":true}
events.js:183
      throw er; // Unhandled 'error' event

**Comment by gperreymond** [comment]
Hello, I use rethinkdbdash under node 8.10 and all work.
Take a look at your options.

**Comment by simpleseeker** [comment]
My apologies. I used the latest driver against a rethink server running version 2.2. When I switched to an older version, it worked.
