### ISSUE TITLE
r.use() usage

### ISSUE THREAD

**Issue by nickpoorman** [neumino/rethinkdbdash#45]
Once I've imported and instantiated the module: `var r = require('rethinkdbdash')()`, is there a way I can set the db on all the connections in the pool or do I have to recreate the pool? Seems like I should be able to do `r.use('testdb')` and it will set everything in the pool to use that database.

My use case for this is when I'm running tests, I tend to instantiate the module without the database because it hasn't been created yet. Once the "test" database is created, from that point on, I want to use the test database but I shouldn't have to re-instantiate (because that would require me to call pool.drain(), wait for it, and then re-instantiate).

**Comment by neumino** [comment]
You can set the `db` per query now.
You cannot do it per connection as you don't explicitly retrieve it from the pool.
