### ISSUE TITLE
conn.close() not working

### ISSUE THREAD

**Issue by pensierinmusica** [neumino/rethinkdbdash#65]
Hi,

For some reason it looks like the db connection is not closing properly.

Running this code (package version 1.16.8), on iojs:

```javascript
r.connect(conf)
  .then(function (conn) {
    conn.close();
  })
```

The process doesn't exit.

Any thoughts? Thanks!

**Comment by neumino** [comment]
Did you import the driver with `{pool : false}`?
If not, you need to call `r.getPool().drain()`.

**Comment by neumino** [comment]
Also, conn.close() return a promise, so you can see if the connection get closed by tackling another `then`.

**Comment by pensierinmusica** [comment]
I see, thanks, this fixes it!  :)
