### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by ufour** [neumino/rethinkdbdash#68]
What's the recommended method for handling errors with this library? Is it necessary to wrap every promise with a .catch or will all errors eventually be propagated somehow?

**Comment by neumino** [comment]
Rethinkdbdash uses bluebird.

You can catch errors with `.error(handler)`. Rethinkdbdash does not require you to use `.catch`. You should use `.cache` if you code can throw, but rethinkdbdash will only return operational errors (see https://github.com/petkaantonov/bluebird/blob/master/API.md#operationalerror)

You can catch your errors at the end of your chain. For example:

```js
r.table('data').get(1).run().then(function(doc1) {
  return r.table('data').get(2).run()
}).then(function(doc2) {
  console.log(doc2);
}).error(function(error) {
  // catch errors from `get(1)` and from `get(2)`
})
```

If you don't like adding `.error` everywhere, you can catch errors on process. See https://github.com/petkaantonov/bluebird/blob/master/API.md#global-rejection-events

Rethinkdbdash currently does not provide to use onPossiblyUnhandledRejection. See https://github.com/petkaantonov/bluebird/blob/master/API.md#promiseonpossiblyunhandledrejectionfunction-handler---undefined
