### ISSUE TITLE
Strange / broken behavior connecting to local Vagrant box

### ISSUE THREAD

**Issue by davewasmer** [neumino/rethinkdbdash#72]
I'm seeing some odd behavior connecting to a Rethinkdb instance running on a Vagrant box on my local Mac. Not sure what this could be, but seems to be isolated to using this driver.

When I run Rethink on the Vagrant box (originally in a Docker container, but I tested running on just the box, and same problem), and try to connect to it, I end up with a bunch of connection timeouts, and the following error:

```
Fail to create a new connection for the connection pool The error returned was:
Failed to connect to docker.dev:28015 in less than 20s.
ReqlDriverError: Failed to connect to docker.dev:28015 in less than 20s.
  at [object Object]._onTimeout (/Users/daw/scratch/node_modules/rethinkdbdash/lib/connection.js:47:16)
  at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)

# several more timeout errors, all appearing simultaneously

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write after end
  at writeAfterEnd (_stream_writable.js:130:12)
  at Socket.Writable.write (_stream_writable.js:178:5)
  at Socket.write (net.js:613:40)
  at Socket.<anonymous> (/Users/daw/scratch/node_modules/rethinkdbdash/lib/connection.js:74:25)
  at Socket.EventEmitter.emit (events.js:117:20)
  at Object.afterConnect [as oncomplete] (net.js:883:10)
```

Gotta love those stream error stack traces ;)

Another odd part. Those errors appear ~20s after creating a pool via `db.createPool` (makes sense - the error timeout is 20s). If I run any commands *before* those timeouts appear, they return successfully, but much slower than normally.

If I use the standard `rethinkdb` driver module, I don't see any problems at all.

I realize this is a bit vague, but I'm not sure where to go next in terms of debugging. Happy to provide more details if you need any.

**Edit:**
Here's [a quick video](http://recordit.co/u4EKRS2heh) demonstrating the issue.

**Comment by neumino** [comment]
Helloe @davewasmer 

So all the errors you see printed are from the pool failing to expand as much as it would like to. By default, the driver will try to keep a pool with at least 50 connections available.

Can you try to import the driver with
```
var r = require('rethinkdbdash')({buffer: 2, max: 5});
```

It will probably work. You can then increase `buffer` and `max` as long as it doesn't break.
I'm not super familiar with Vagrant or its default settings so I can't give you more precise numbers.

As for the error "write after close", this is actually a bug. I guess a connection can fire the event "connect" while being closed. 
I'm currently working on pools with multiple servers, I'll push the fix at the same time.

**Comment by neumino** [comment]
Closing, feel free to reopen if you have the same problem when using less connections.
