### ISSUE TITLE
Strange behavior of type.array()

### ISSUE THREAD

**Issue by zlls** [neumino/rethinkdbdash#75]
I tried out this awesome library today, but I came across a strange behavior while validating arrays.

So I want an array with objects inside. Each Object should contain required keys (key2) and optional keys (key3). Here is an example:

```javascript
    var Test = thinky.createModel("Test", {
        // ...
        "test": type.array().schema(
            type.object().schema({
                "key1": type.number(),
                "key2": type.string().required(),
                "key3": type.string().optional()
            })
        ).required()
    });
```
If I use ```type.array().schema( /* ... */ ).required()``` every key in the array is required. But if I use ```type.array().schema( /* ... */ )``` instead of ```type.array().schema( /* ... */ ).required()```, it ignores any ```.required()``` and ```.optional()``` inside the array.

Am I misunderstanding how to use the validation or is it not just me?

**Comment by neumino** [comment]
Hello @zlls 

This is a bug, I just opened https://github.com/neumino/thinky/issues/203 (wrong repository)
I'll look into it
