### ISSUE TITLE
Expose pre-flight hook for requests

### ISSUE THREAD

**Issue by Zolmeister** [neumino/rethinkdbdash#77]
For those not using an ORM, it is still useful to be stateless and create missing databases/tables necessary for an application without having to explicitly declare it (and wait).

Idea is to expose a method which may return a promise that is in charge of setting up initial state (creating missing databases, tables, etc) before requests are allowed to run.

**Comment by neumino** [comment]
You can just start your app once your promises are resolved. I'm not sure what the driver can do more for you.

```
var r = require('rethinkdbdash')();
var bluebird = require('bluebird');
var promises = [];
promises.push( r.tableCreate("foo").run() );
promises.push( r.tableCreate("bar").run() );

var express = require('express');
var app = express.createServer();
app.get('/', function(req, res){
    res.send('Hello World');
});

bluebird.all(promises).then(function() {
  app.listen();
})
```

**Comment by Zolmeister** [comment]
Yes, that's how I do it now. It's just ugly :frowning:
A setting like `createIfNotExist: true` would clean it up, but I guess the benefits are small.

Thanks for considering it though

**Comment by neumino** [comment]
@Zolmeister -- you may want to chime in this issue (automatically creating table) https://github.com/rethinkdb/rethinkdb/issues/2355

You would still have to manually create indexes though.

On a side note, if you use a coreos cluster, you can just tell fleetctl to start your app only after running a certain script.
