### ISSUE TITLE
PoolMaster does not recover from connectivity outages

### ISSUE THREAD

**Issue by simonratner** [neumino/rethinkdbdash#84]
PoolMaster maintains a set of healthy pools:
* When a pool is created, it is added to healthyPools;
* When a pool becomes empty, it is removed from healthyPools;
* When a pool becomes non-empty, it is re-added to healthyPools;
* When looking for an available connection, only pools in healthyPools are considered.

Once a pool becomes empty by means other than a connection timeout (for example, connections can be gracefully terminated by a load balancer, or simply by restarting rethinkdb), there is no way for that pool to become non-empty again. PoolMaster will not consider this pool in its search for connections, hence it will never call Pool.createConnection which causes the pool to refill. The result is a dead PoolMaster that has no available connections, even after rethinkdb connectivity is restored.

To reproduce, run the following script, restart rethinkdb, and observe that the pool never recovers.
```js
var r = require('rethinkdbdash')({
    buffer: 2,
    max: 2,
    pool: true,
    silent: true,
    discovery: false,
    servers: [
        { host: 'localhost', port: 28015 }
    ]});

r.getPoolMaster().getPools().forEach(function(pool) {
    ['created-connection', 'empty', 'not-empty'].forEach(function(ev) {
        pool.on(ev, function() {
            console.log('[' + ev + ']');
        });
    });
});
r.getPoolMaster().on('size', function(num) {
    if (num == 0) {
        console.log('[all pool empty]');
    }
});

var query = function() {
    r.db('rethinkdb').table('server_status').then(function(servers) {
        console.log('ok', servers.length);
    }).catch(function(err) {
        console.log(err);
    });
};

setInterval(query, 2000);
query();
```

I noticed that reconnect after connection termination was removed in https://github.com/neumino/rethinkdbdash/commit/13735f7943742d49b962bdd61e2f2072650b0020#diff-bbb580747701b731142b6584ae61643bL216. Was this an intentional change, and if so, what was the reason behind it? Reintroducing the commented line makes the above behave as expected: once rethinkdb comes back up, the connection retry logic eventually succeeds and the pool recovers.

**Comment by neumino** [comment]
Hum, looking into it.

It seems to work fine in discovery mode, which:
- make things less crazy as I remembered testing this kind of things
- make things more crazy as this shouldn't impact each pool recovery.

Thanks for the report @simonratner

**Comment by neumino** [comment]
Hum, the behavior of socket.write changed since last time too. It seems connection.write will throw and not emit an error -_-

**Comment by simonratner** [comment]
Yup, I hadn't noticed the problem until two days ago, when you flipped discovery from default true to default false.

**Comment by neumino** [comment]
Ah, I think I found the problem. The pool doesn't actually enter in slow growth because it doesn't try to reopen a connection when the server dies.

I'll also wrap the socket.write since it's not save anymore -_-

**Comment by simonratner** [comment]
While you are there, there is also an obvious issue with the spreading/trimming of buffer and max values when the number of healthy pools hits zero: you get lots of fun Infinities ;)

**Comment by simonratner** [comment]
Actually, just ignoring the zeros doesn't really work in that case, since then when the pools return from the dead they end up with wrong `buffer` and `max` values. 

I think you need to recalculate the `buffer` and `max` values from the original config each time the size of healthy pool set changes, just like you do in discovery mode with `resetBufferParameters()`.

**Comment by neumino** [comment]
Out in 2.0.3

**Comment by simonratner** [comment]
Awesome, thank you @neumino! 
I have filed a separate issue #85 for the connection limit counts.
