### ISSUE TITLE
Table Create options do not match REQL api docs for NodeJS

### ISSUE THREAD

**Issue by suparngp** [neumino/rethinkdbdash#86]
Use case: Create a table with shards and replicas
Options Passed:
<pre>
<code>
{
    "primaryKey":"blog_id",
    "durability":"hard",
    "shards":2,
    "replicas":2
}
</code>
</pre>

Output:
{ [ReqlDriverError: Unrecognized option `shards` in `tableCreate` after:
r.db("test")
Available options are primaryKey <string>, durability <string>, datancenter <string>]
  message: 'Unrecognized option `shards` in `tableCreate` after:\nr.db("test")\nAvailable options are primaryKey <string>, durability <string>, datancenter <string>' }

The same query works fine in Data Explorer.

**Comment by neumino** [comment]
Thanks for the report, looks like I forgot to update this for 2.0. I'll push a fix in a few minutes.

**Comment by suparngp** [comment]
Wow, this is probably the fastest reply on Git.

Thanks!

**Comment by neumino** [comment]
Fixed in 2.0.6 -- thanks @suparngp
