### ISSUE TITLE
Using primaryReplicaTag throws Error in tableCreate

### ISSUE THREAD

**Issue by suparngp** [neumino/rethinkdbdash#87]
Environment: 2 servers running locally, with tags us_east and us_west (One tag assigned to either server).
Query:
<pre>
<code> 
r.db("test").tableCreate("girlfriends",
{
    replicas: {"us_east": 1, "us_west":1}, 
    shards: 2, 
    primaryReplicaTag: "us_west"
}).run()
</code>
</pre>
Output:
<pre>
<code>
{ [ReqlCompileError: Unrecognized optional argument `primaryReplicaTag` in:
r.db("test").tableCreate("girlfriends", {
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    replicas: {
    ^^^^^^^^^^^
        us_east: 1,
        ^^^^^^^^^^^
        us_west: 1
        ^^^^^^^^^^
    },
    ^^
    shards: 2,
    ^^^^^^^^^^
    primaryReplicaTag: "us_west"
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
})
^^
]
  message: 'Unrecognized optional argument `primaryReplicaTag` in:\nr.db("test").tableCreate("girlfriends", {\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    replicas: {\n    ^^^^^^^^^^^\n        us_east: 1,\n        ^^^^^^^^^^^\n        us_west: 1\n        ^^^^^^^^^^\n    },\n    ^^\n    shards: 2,\n    ^^^^^^^^^^\n    primaryReplicaTag: "us_west"\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n})\n^^\n',
  frames: [] }

</code>
</pre>

The same query works fine in Data Explorer. 

Also, the error message which shows up when an unrecognized option is passed needs a fix, 

<code>
Available options are primaryKey <string>, durability <string>,
 shards <number>, replicas <number/object>, primaryReplicaTag <object>
</code>

The type of primaryReplicaTag should be a string.

**Comment by neumino** [comment]
I forgot to underscore the option earlier.
Should be fixed in 2.0.7

**Comment by suparngp** [comment]
Thanks @neumino

**Comment by suparngp** [comment]
A typo.

primaryReplicaTag, 'primary_replica_tag' Line 2708

Throws compile error.

**Comment by neumino** [comment]
Err, I should have tested it before -_-.
Should be fixed in 2.0.8 this time :)

**Comment by suparngp** [comment]
LoL, verified, its working :+1: . Update the error message when ever you get a chance. term.js, Line 361, primaryReplicaTag <object> --> <string>
