### ISSUE TITLE
Failed to connect to localhost:28015

### ISSUE THREAD

**Issue by terrytornado** [neumino/rethinkdbdash#88]
Seems the error is not away (2.0.9):

var r = require('rethinkdbdash')((
{
    pool: false,
    cursor: true,
    timeout: 30,
    db: 'test',
    servers: [
        {host: '112.168.100.19', port: 28015}
    ]
}));

r.connect(function (err, conn) {
    console.log(err);
    console.log(conn);
});

ERROR:
{ [ReqlDriverError: Failed to connect to localhost:28015
Full error:
{
  "code": "ECONNREFUSED",
  "errno": "ECONNREFUSED",
  "syscall": "connect"
}.]
  message: 'Failed to connect to localhost:28015\nFull error:\n{\n  "code": "ECONNREFUSED",\n  "errno": "ECONNREFUSED",\n  "syscall": "connect"\n}.' }
undefined

**Comment by neumino** [comment]
The settings `{host: '112.168.100.19', port: 28015}` are used only for the pool, not by default with `r.connect`.

This is probably what you want:
```
r.connect({host: '112.168.100.19', port: 28015}, function(err, conn) {
  // ...
})
```

**Comment by terrytornado** [comment]
Thanks Michael,

works now:

// rethinkdbdash must be executed with '()' by instantiating.
var r = require('rethinkdbdash')({
        timeout: 60,
        db: 'test',
        servers:[
            {host: '192.168.100.19', port: 28015}
        ],
        buffer: 300,
        max: 3000
    });


module.exports = {
    rethinkdb: r
};
