### ISSUE TITLE
How do I properly close down a connection?

### ISSUE THREAD

**Issue by aweijnitz** [neumino/rethinkdbdash#91]
The official driver has 'close', see http://www.rethinkdb.com/api/javascript/close/

I can't find a corresponding API to close down all connections in the pool and exit on completion.

**Comment by neumino** [comment]
```
r.getPoolMaster().drain();
```
See https://github.com/neumino/rethinkdbdash/blob/master/README.md

**Comment by aweijnitz** [comment]
Thanks!
