### ISSUE TITLE
Cannot create connection for the pool while using thinky

### ISSUE THREAD

**Issue by mkorablin** [neumino/rethinkdbdash#93]
I'm getting the following error trying to startup a server:

    Fail to create a new connection for the connection pool The error returned was:
    Failed to connect to localhost:28015
    Full error:
    {
      "code": "EMFILE",
      "errno": "EMFILE",
      "syscall": "connect"
    }.
    ReqlDriverError: Failed to connect to localhost:28015
    Full error:
    {
      "code": "EMFILE",
      "errno": "EMFILE",
      "syscall": "connect"
    }.
        at Socket.<anonymous> (..../node_modules/rethinkdbdash/lib/connection.js:89:12)
        at Socket.g (events.js:180:16)
        at Socket.EventEmitter.emit (events.js:95:17)
        at net.js:440:14
        at process._tickCallback (node.js:415:13)

`EMFILE` means that I'm running against the limit of open files.

I've narrowed it down to the fact that I'm creating several models each of those have the following code:

    var thinky = require('thinky')();

I suspect that when I create `thinky` instance it creates `rethinkdbdash` instance which creates `r` instance every time and with that a connection pool with a limit of 1000. So when I require my models, I eventually hit the limit. If I load fewer models (I believe less than 4), it's all fine.

What's the best way to resolve this? I don't want to combine all models into one file.

**Comment by neumino** [comment]
You are supposed to create one instance of thinky -- see http://thinky.io/documentation/architecture/

**Comment by mkorablin** [comment]
Aaah, completely missed that. Thanks!
