### ISSUE TITLE
Unsubscribe to a feed

### ISSUE THREAD

**Issue by devmarco** [neumino/rethinkdbdash#96]
Subscribe to a feed is very simple

```
r.table('users').changes().run().then(function(result) {
      console.log(result);
});
```

But how i can unsubscribe to this feed?

**Comment by neumino** [comment]
With `close`.

```
result.close()
```
http://www.rethinkdb.com/api/javascript/close/

**Comment by devmarco** [comment]
Have an way to get an existent feed?

Because i have an API where have a service for create notification, where i have two endpoints:

/api/notification/ [POST]
/api/notification/ [DELETE]

Where i can create and delete a user of a notification.
How the only way to unsubscribe to a feed, is calling "cursor.close()" and cursor is a callback of a function, the only way that i can see that i can use this system in my application is when i create a notification, I will store the cursor in a variable, and when the user cancel the notification, I will get your cursor in my variable and close it.

But this is a bad solution because if my application is gonna down, i will lost all cursors, should have a way to get the cursor like that:

r.changefeed(1).close() //Get and close the cursor for feed 1

But how this not exist, can you help me with a better solution for do this in my app?

**Comment by marshall007** [comment]
@devmarco see rethinkdb/rethinkdb#3471

**Comment by neumino** [comment]
Yep, like @marshall007 pointed out, changefeeds are currently not synced to disk, and there is little the driver can do to provide this functionality. You need to chime in the RethinkDB issue
